package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-05-30T22:48:28.261-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "IExternalFleetMgmtService")
@XmlSeeAlso({com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, org.datacontract.schemas._2004._07.tmix_cap_fleetmgmt_library_wcf_external_service_data.ObjectFactory.class, org.contract.ObjectFactory.class})
public interface IExternalFleetMgmtService {

    @WebMethod(operationName = "GetVehicleEvents", action = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleEvents")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleEvents", output = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleEventsResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetVehicleEventsFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleEventsFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetVehicleEvents", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleEvents")
    @ResponseWrapper(localName = "GetVehicleEventsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleEventsResponse")
    @WebResult(name = "GetVehicleEventsResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfEventDataType getVehicleEvents(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session,
        @WebParam(name = "vehicleIds", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint vehicleIds,
        @WebParam(name = "events", targetNamespace = "http://tempuri.org/")
        org.contract.ArrayOfEventTypeType events,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar to
    ) throws IExternalFleetMgmtServiceGetVehicleEventsFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "Logout", action = "http://tempuri.org/IExternalFleetMgmtService/Logout")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/Logout", output = "http://tempuri.org/IExternalFleetMgmtService/LogoutResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceLogoutFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/LogoutFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "Logout", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LogoutResponse")
    public void logout(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session
    ) throws IExternalFleetMgmtServiceLogoutFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetStandardFuelConsumption", action = "http://tempuri.org/IExternalFleetMgmtService/GetStandardFuelConsumption")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetStandardFuelConsumption", output = "http://tempuri.org/IExternalFleetMgmtService/GetStandardFuelConsumptionResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetStandardFuelConsumptionFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetStandardFuelConsumptionFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetStandardFuelConsumption", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStandardFuelConsumption")
    @ResponseWrapper(localName = "GetStandardFuelConsumptionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStandardFuelConsumptionResponse")
    @WebResult(name = "GetStandardFuelConsumptionResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfStandardFuelConsumptionDataType getStandardFuelConsumption(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session
    ) throws IExternalFleetMgmtServiceGetStandardFuelConsumptionFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDriverSpeedIntervals", action = "http://tempuri.org/IExternalFleetMgmtService/GetDriverSpeedIntervals")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetDriverSpeedIntervals", output = "http://tempuri.org/IExternalFleetMgmtService/GetDriverSpeedIntervalsResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetDriverSpeedIntervalsFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetDriverSpeedIntervalsFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetDriverSpeedIntervals", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDriverSpeedIntervals")
    @ResponseWrapper(localName = "GetDriverSpeedIntervalsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDriverSpeedIntervalsResponse")
    @WebResult(name = "GetDriverSpeedIntervalsResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfDriverIntervalDataType getDriverSpeedIntervals(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session,
        @WebParam(name = "driverIds", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint driverIds,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar to
    ) throws IExternalFleetMgmtServiceGetDriverSpeedIntervalsFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDriverParameters", action = "http://tempuri.org/IExternalFleetMgmtService/GetDriverParameters")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetDriverParameters", output = "http://tempuri.org/IExternalFleetMgmtService/GetDriverParametersResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetDriverParametersFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetDriverParametersFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetDriverParameters", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDriverParameters")
    @ResponseWrapper(localName = "GetDriverParametersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDriverParametersResponse")
    @WebResult(name = "GetDriverParametersResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfDriverParameterDataType getDriverParameters(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session,
        @WebParam(name = "driverIds", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint driverIds,
        @WebParam(name = "parameters", targetNamespace = "http://tempuri.org/")
        org.contract.ArrayOfParameterTypeType parameters,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar to
    ) throws IExternalFleetMgmtServiceGetDriverParametersFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetVehiclePositions", action = "http://tempuri.org/IExternalFleetMgmtService/GetVehiclePositions")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetVehiclePositions", output = "http://tempuri.org/IExternalFleetMgmtService/GetVehiclePositionsResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetVehiclePositionsFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetVehiclePositions", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehiclePositions")
    @ResponseWrapper(localName = "GetVehiclePositionsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehiclePositionsResponse")
    @WebResult(name = "GetVehiclePositionsResult", targetNamespace = "http://tempuri.org/")
    public com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOfintArrayOfTimedPositionfi2YCEuP getVehiclePositions(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session,
        @WebParam(name = "vehicleIds", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint vehicleIds,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar to
    ) throws IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDriverEvents", action = "http://tempuri.org/IExternalFleetMgmtService/GetDriverEvents")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetDriverEvents", output = "http://tempuri.org/IExternalFleetMgmtService/GetDriverEventsResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetDriverEventsFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetDriverEventsFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetDriverEvents", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDriverEvents")
    @ResponseWrapper(localName = "GetDriverEventsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDriverEventsResponse")
    @WebResult(name = "GetDriverEventsResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfEventDataType getDriverEvents(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session,
        @WebParam(name = "driverIds", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint driverIds,
        @WebParam(name = "events", targetNamespace = "http://tempuri.org/")
        org.contract.ArrayOfEventTypeType events,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar to
    ) throws IExternalFleetMgmtServiceGetDriverEventsFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetDrivers", action = "http://tempuri.org/IExternalFleetMgmtService/GetDrivers")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetDrivers", output = "http://tempuri.org/IExternalFleetMgmtService/GetDriversResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetDriversFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetDriversFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetDrivers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDrivers")
    @ResponseWrapper(localName = "GetDriversResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDriversResponse")
    @WebResult(name = "GetDriversResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfDriverType getDrivers(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session
    ) throws IExternalFleetMgmtServiceGetDriversFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetCompanies", action = "http://tempuri.org/IExternalFleetMgmtService/GetCompanies")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetCompanies", output = "http://tempuri.org/IExternalFleetMgmtService/GetCompaniesResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetCompaniesFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetCompaniesFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetCompanies", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCompanies")
    @ResponseWrapper(localName = "GetCompaniesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCompaniesResponse")
    @WebResult(name = "GetCompaniesResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfCompanyType getCompanies(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session
    ) throws IExternalFleetMgmtServiceGetCompaniesFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetVehicleSpeedIntervals", action = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleSpeedIntervals")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleSpeedIntervals", output = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleSpeedIntervalsResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetVehicleSpeedIntervalsFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleSpeedIntervalsFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetVehicleSpeedIntervals", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleSpeedIntervals")
    @ResponseWrapper(localName = "GetVehicleSpeedIntervalsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleSpeedIntervalsResponse")
    @WebResult(name = "GetVehicleSpeedIntervalsResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfVehicleIntervalDataType getVehicleSpeedIntervals(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session,
        @WebParam(name = "vehicleIds", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint vehicleIds,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar to
    ) throws IExternalFleetMgmtServiceGetVehicleSpeedIntervalsFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "Login", action = "http://tempuri.org/IExternalFleetMgmtService/Login")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/Login", output = "http://tempuri.org/IExternalFleetMgmtService/LoginResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceLoginFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/LoginFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "Login", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Login")
    @ResponseWrapper(localName = "LoginResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String login(
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        java.lang.String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    ) throws IExternalFleetMgmtServiceLoginFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetVehicles", action = "http://tempuri.org/IExternalFleetMgmtService/GetVehicles")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetVehicles", output = "http://tempuri.org/IExternalFleetMgmtService/GetVehiclesResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetVehiclesFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetVehiclesFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetVehicles", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicles")
    @ResponseWrapper(localName = "GetVehiclesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehiclesResponse")
    @WebResult(name = "GetVehiclesResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfVehicleType getVehicles(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session
    ) throws IExternalFleetMgmtServiceGetVehiclesFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetVehicleParameters", action = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleParameters")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleParameters", output = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleParametersResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetVehicleParametersFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetVehicleParametersFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetVehicleParameters", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleParameters")
    @ResponseWrapper(localName = "GetVehicleParametersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVehicleParametersResponse")
    @WebResult(name = "GetVehicleParametersResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfVehicleParameterDataType getVehicleParameters(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session,
        @WebParam(name = "vehicleIds", targetNamespace = "http://tempuri.org/")
        com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfint vehicleIds,
        @WebParam(name = "parameters", targetNamespace = "http://tempuri.org/")
        org.contract.ArrayOfParameterTypeType parameters,
        @WebParam(name = "from", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar from,
        @WebParam(name = "to", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar to
    ) throws IExternalFleetMgmtServiceGetVehicleParametersFleetMgmtExceptionFaultFaultMessage;

    @WebMethod(operationName = "GetUsers", action = "http://tempuri.org/IExternalFleetMgmtService/GetUsers")
    @Action(input = "http://tempuri.org/IExternalFleetMgmtService/GetUsers", output = "http://tempuri.org/IExternalFleetMgmtService/GetUsersResponse", fault = {@FaultAction(className = IExternalFleetMgmtServiceGetUsersFleetMgmtExceptionFaultFaultMessage.class, value = "http://tempuri.org/IExternalFleetMgmtService/GetUsersFleetMgmtExceptionFault")})
    @RequestWrapper(localName = "GetUsers", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUsers")
    @ResponseWrapper(localName = "GetUsersResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetUsersResponse")
    @WebResult(name = "GetUsersResult", targetNamespace = "http://tempuri.org/")
    public org.contract.ArrayOfUserType getUsers(
        @WebParam(name = "session", targetNamespace = "http://tempuri.org/")
        java.lang.String session
    ) throws IExternalFleetMgmtServiceGetUsersFleetMgmtExceptionFaultFaultMessage;
}
