
package org.tempuri;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2018-05-30T22:48:28.194-05:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "FleetMgmtException", targetNamespace = "http://schemas.datacontract.org/2004/07/Tmix.Cap.FleetMgmt.Library.Wcf.External.Service.Data.Exception")
public class IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage extends Exception {
    
    private org.datacontract.schemas._2004._07.tmix_cap_fleetmgmt_library_wcf_external_service_data.FleetMgmtException fleetMgmtException;

    public IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage() {
        super();
    }
    
    public IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage(String message) {
        super(message);
    }
    
    public IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.tmix_cap_fleetmgmt_library_wcf_external_service_data.FleetMgmtException fleetMgmtException) {
        super(message);
        this.fleetMgmtException = fleetMgmtException;
    }

    public IExternalFleetMgmtServiceGetVehiclePositionsFleetMgmtExceptionFaultFaultMessage(String message, org.datacontract.schemas._2004._07.tmix_cap_fleetmgmt_library_wcf_external_service_data.FleetMgmtException fleetMgmtException, Throwable cause) {
        super(message, cause);
        this.fleetMgmtException = fleetMgmtException;
    }

    public org.datacontract.schemas._2004._07.tmix_cap_fleetmgmt_library_wcf_external_service_data.FleetMgmtException getFaultInfo() {
        return this.fleetMgmtException;
    }
}
