
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wirelesscar.dynafleet.api;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.596-05:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "DynafleetAPI",
                      portName = "DTMServicePort",
                      targetNamespace = "http://wirelesscar.com/dynafleet/api",
                      wsdlLocation = "https://api-preprod.dynafleetonline.com/wsdl",
                      endpointInterface = "com.wirelesscar.dynafleet.api.DTMService")
                      
public class DTMServiceImpl implements DTMService {

    private static final Logger LOG = Logger.getLogger(DTMServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.DTMService#getDTMAlarmsForVehicle(com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmsForVehicleTO  apiDTMGetDTMAlarmsForVehicleTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO getDTMAlarmsForVehicle(com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmsForVehicleTO apiDTMGetDTMAlarmsForVehicleTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDTMAlarmsForVehicle");
        System.out.println(apiDTMGetDTMAlarmsForVehicleTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO>();
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO();
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1DTMAlarmId = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1DTMAlarmId.setValue(589881094683883045l);
            _returnArrayVal1.setDTMAlarmId(_returnArrayVal1DTMAlarmId);
            _returnArrayVal1.setDTMAlarmType("DTMAlarmType-1320085153");
            _returnArrayVal1.setDriverActivityType("DriverActivityType-55342294");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(-8401024065362684660l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1EstimatedTimeOfRuleBreak = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1EstimatedTimeOfRuleBreak.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.600-05:00"));
            _returnArrayVal1.setEstimatedTimeOfRuleBreak(_returnArrayVal1EstimatedTimeOfRuleBreak);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsDeleted.setValue(true);
            _returnArrayVal1.setIsDeleted(_returnArrayVal1IsDeleted);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.601-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(-9130871842531834066l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.DTMService#getNewDTMAlarmSetupSendStatuses(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusArrayTO getNewDTMAlarmSetupSendStatuses(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewDTMAlarmSetupSendStatuses");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusTO>();
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusTO();
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1LatestSendstatusTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1LatestSendstatusTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.602-05:00"));
            _returnArrayVal1.setLatestSendstatusTime(_returnArrayVal1LatestSendstatusTime);
            _returnArrayVal1.setSendstatus("Sendstatus-1227347091");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(6128719615145988906l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.DTMService#getNewDTMAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO getNewDTMAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewDTMAlarms");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO>();
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiDTMAlarmTO();
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1DTMAlarmId = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1DTMAlarmId.setValue(7825159239329906102l);
            _returnArrayVal1.setDTMAlarmId(_returnArrayVal1DTMAlarmId);
            _returnArrayVal1.setDTMAlarmType("DTMAlarmType1981040626");
            _returnArrayVal1.setDriverActivityType("DriverActivityType-2052127607");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(7681153926352453208l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1EstimatedTimeOfRuleBreak = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1EstimatedTimeOfRuleBreak.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.602-05:00"));
            _returnArrayVal1.setEstimatedTimeOfRuleBreak(_returnArrayVal1EstimatedTimeOfRuleBreak);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsDeleted.setValue(true);
            _returnArrayVal1.setIsDeleted(_returnArrayVal1IsDeleted);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.603-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(7116051513411306031l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.DTMService#getDTMAlarmSetting(com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmSettingTO  apiDTMGetDTMAlarmSettingTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSettingTO getDTMAlarmSetting(com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmSettingTO apiDTMGetDTMAlarmSettingTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDTMAlarmSetting");
        System.out.println(apiDTMGetDTMAlarmSettingTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSettingTO _return = new com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSettingTO();
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnAlarmOn = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnAlarmOn.setValue(false);
            _return.setAlarmOn(_returnAlarmOn);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnLatestSendStatusTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnLatestSendStatusTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.603-05:00"));
            _return.setLatestSendStatusTime(_returnLatestSendStatusTime);
            _return.setSendStatus("SendStatus2054533018");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnVehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnVehicleId.setId(-4553572919194830077l);
            _return.setVehicleId(_returnVehicleId);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.DTMService#storeDTMAlarmSetting(com.wirelesscar.dynafleet.api.types.ApiDTMStoreDTMAlarmSettingTO  apiDTMStoreDTMAlarmSettingTO1 )*
     */
    public void storeDTMAlarmSetting(com.wirelesscar.dynafleet.api.types.ApiDTMStoreDTMAlarmSettingTO apiDTMStoreDTMAlarmSettingTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation storeDTMAlarmSetting");
        System.out.println(apiDTMStoreDTMAlarmSettingTO1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.DTMService#getDeletedDTMAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiLongArrayTO getDeletedDTMAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDeletedDTMAlarms");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiLongArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiLong> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLong>();
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1.setValue(6575598563123784416l);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

}
