
package com.wirelesscar.dynafleet.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.416-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class DTMService_DTMServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://wirelesscar.com/dynafleet/api", "DynafleetAPI");

    private DTMService_DTMServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DynafleetAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DynafleetAPI ss = new DynafleetAPI(wsdlURL, SERVICE_NAME);
        DTMService port = ss.getDTMServicePort();  
        
        {
        System.out.println("Invoking getDTMAlarmsForVehicle...");
        com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmsForVehicleTO _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1 = new com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmsForVehicleTO();
        com.wirelesscar.dynafleet.api.types.ApiDate _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1FromDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1FromDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.424-05:00"));
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1.setFromDate(_getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1FromDate);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1SessionId.setId("Id1346659988");
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1.setSessionId(_getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1SessionId);
        com.wirelesscar.dynafleet.api.types.ApiDate _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1ToDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1ToDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.424-05:00"));
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1.setToDate(_getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1ToDate);
        com.wirelesscar.dynafleet.api.types.ApiVehicleId _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1VehicleId.setId(3944781407761680626l);
        _getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1.setVehicleId(_getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1VehicleId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO _getDTMAlarmsForVehicle__return = port.getDTMAlarmsForVehicle(_getDTMAlarmsForVehicle_apiDTMGetDTMAlarmsForVehicleTO1);
            System.out.println("getDTMAlarmsForVehicle.result=" + _getDTMAlarmsForVehicle__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNewDTMAlarmSetupSendStatuses...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getNewDTMAlarmSetupSendStatuses_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getNewDTMAlarmSetupSendStatuses_apiSessionId1.setId("Id437916703");
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSetupSendstatusArrayTO _getNewDTMAlarmSetupSendStatuses__return = port.getNewDTMAlarmSetupSendStatuses(_getNewDTMAlarmSetupSendStatuses_apiSessionId1);
            System.out.println("getNewDTMAlarmSetupSendStatuses.result=" + _getNewDTMAlarmSetupSendStatuses__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNewDTMAlarms...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getNewDTMAlarms_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getNewDTMAlarms_apiSessionId1.setId("Id-151284351");
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmArrayTO _getNewDTMAlarms__return = port.getNewDTMAlarms(_getNewDTMAlarms_apiSessionId1);
            System.out.println("getNewDTMAlarms.result=" + _getNewDTMAlarms__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDTMAlarmSetting...");
        com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmSettingTO _getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1 = new com.wirelesscar.dynafleet.api.types.ApiDTMGetDTMAlarmSettingTO();
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1SessionId.setId("Id890861899");
        _getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1.setSessionId(_getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1SessionId);
        com.wirelesscar.dynafleet.api.types.ApiVehicleId _getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
        _getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1VehicleId.setId(7420658131750825605l);
        _getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1.setVehicleId(_getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1VehicleId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDTMAlarmSettingTO _getDTMAlarmSetting__return = port.getDTMAlarmSetting(_getDTMAlarmSetting_apiDTMGetDTMAlarmSettingTO1);
            System.out.println("getDTMAlarmSetting.result=" + _getDTMAlarmSetting__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking storeDTMAlarmSetting...");
        com.wirelesscar.dynafleet.api.types.ApiDTMStoreDTMAlarmSettingTO _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1 = new com.wirelesscar.dynafleet.api.types.ApiDTMStoreDTMAlarmSettingTO();
        com.wirelesscar.dynafleet.api.types.ApiBoolean _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1AlarmOn = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1AlarmOn.setValue(true);
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1.setAlarmOn(_storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1AlarmOn);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1SessionId.setId("Id-1070805923");
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1.setSessionId(_storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1SessionId);
        com.wirelesscar.dynafleet.api.types.ApiVehicleId _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1VehicleId.setId(-2812326210709405739l);
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1.setVehicleId(_storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1VehicleId);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1WarningOn = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1WarningOn.setValue(false);
        _storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1.setWarningOn(_storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1WarningOn);
        try {
            port.storeDTMAlarmSetting(_storeDTMAlarmSetting_apiDTMStoreDTMAlarmSettingTO1);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDeletedDTMAlarms...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getDeletedDTMAlarms_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getDeletedDTMAlarms_apiSessionId1.setId("Id-1982661816");
        try {
            com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _getDeletedDTMAlarms__return = port.getDeletedDTMAlarms(_getDeletedDTMAlarms_apiSessionId1);
            System.out.println("getDeletedDTMAlarms.result=" + _getDeletedDTMAlarms__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
