
package com.wirelesscar.dynafleet.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.474-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class FormService_FormServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://wirelesscar.com/dynafleet/api", "DynafleetAPI");

    private FormService_FormServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DynafleetAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DynafleetAPI ss = new DynafleetAPI(wsdlURL, SERVICE_NAME);
        FormService port = ss.getFormServicePort();  
        
        {
        System.out.println("Invoking getForms...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getForms_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getForms_apiSessionId1.setId("Id-1874622370");
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormArrayTO _getForms__return = port.getForms(_getForms_apiSessionId1);
            System.out.println("getForms.result=" + _getForms__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getFormsInVehicle...");
        com.wirelesscar.dynafleet.api.types.ApiFormGetFormsInVehicleTO _getFormsInVehicle_apiFormGetFormsInVehicleTO1 = new com.wirelesscar.dynafleet.api.types.ApiFormGetFormsInVehicleTO();
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getFormsInVehicle_apiFormGetFormsInVehicleTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getFormsInVehicle_apiFormGetFormsInVehicleTO1SessionId.setId("Id384581387");
        _getFormsInVehicle_apiFormGetFormsInVehicleTO1.setSessionId(_getFormsInVehicle_apiFormGetFormsInVehicleTO1SessionId);
        com.wirelesscar.dynafleet.api.types.ApiVehicleId _getFormsInVehicle_apiFormGetFormsInVehicleTO1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
        _getFormsInVehicle_apiFormGetFormsInVehicleTO1VehicleId.setId(-2946945806917401314l);
        _getFormsInVehicle_apiFormGetFormsInVehicleTO1.setVehicleId(_getFormsInVehicle_apiFormGetFormsInVehicleTO1VehicleId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormArrayTO _getFormsInVehicle__return = port.getFormsInVehicle(_getFormsInVehicle_apiFormGetFormsInVehicleTO1);
            System.out.println("getFormsInVehicle.result=" + _getFormsInVehicle__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getForm...");
        com.wirelesscar.dynafleet.api.types.ApiFormGetFormTO _getForm_apiFormGetFormTO1 = new com.wirelesscar.dynafleet.api.types.ApiFormGetFormTO();
        com.wirelesscar.dynafleet.api.types.ApiFormId _getForm_apiFormGetFormTO1FormId = new com.wirelesscar.dynafleet.api.types.ApiFormId();
        _getForm_apiFormGetFormTO1FormId.setId(7145957291185567751l);
        _getForm_apiFormGetFormTO1.setFormId(_getForm_apiFormGetFormTO1FormId);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _getForm_apiFormGetFormTO1MessageForm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _getForm_apiFormGetFormTO1MessageForm.setValue(true);
        _getForm_apiFormGetFormTO1.setMessageForm(_getForm_apiFormGetFormTO1MessageForm);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getForm_apiFormGetFormTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getForm_apiFormGetFormTO1SessionId.setId("Id429836745");
        _getForm_apiFormGetFormTO1.setSessionId(_getForm_apiFormGetFormTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormTO _getForm__return = port.getForm(_getForm_apiFormGetFormTO1);
            System.out.println("getForm.result=" + _getForm__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
