package com.wirelesscar.dynafleet.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.687-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wirelesscar.com/dynafleet/api", name = "FormService")
@XmlSeeAlso({com.wirelesscar.dynafleet.api.types.ObjectFactory.class})
public interface FormService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getForms", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetForms")
    @WebMethod
    @ResponseWrapper(localName = "getFormsResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetFormsResponse")
    public com.wirelesscar.dynafleet.api.types.ApiFormArrayTO getForms(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getFormsInVehicle", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetFormsInVehicle")
    @WebMethod
    @ResponseWrapper(localName = "getFormsInVehicleResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetFormsInVehicleResponse")
    public com.wirelesscar.dynafleet.api.types.ApiFormArrayTO getFormsInVehicle(
        @WebParam(name = "Api_FormGetFormsInVehicleTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiFormGetFormsInVehicleTO apiFormGetFormsInVehicleTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getForm", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetForm")
    @WebMethod
    @ResponseWrapper(localName = "getFormResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetFormResponse")
    public com.wirelesscar.dynafleet.api.types.ApiFormTO getForm(
        @WebParam(name = "Api_FormGetFormTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiFormGetFormTO apiFormGetFormTO1
    ) throws DynafleetAPIException;
}
