
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wirelesscar.dynafleet.api;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.587-05:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "DynafleetAPI",
                      portName = "FormMessageServicePort",
                      targetNamespace = "http://wirelesscar.com/dynafleet/api",
                      wsdlLocation = "https://api-preprod.dynafleetonline.com/wsdl",
                      endpointInterface = "com.wirelesscar.dynafleet.api.FormMessageService")
                      
public class FormMessageServiceImpl implements FormMessageService {

    private static final Logger LOG = Logger.getLogger(FormMessageServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#getFormMessagesByForm(com.wirelesscar.dynafleet.api.types.ApiFormMessageGetFormMessagesByFormTO  apiFormMessageGetFormMessagesByFormTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO getFormMessagesByForm(com.wirelesscar.dynafleet.api.types.ApiFormMessageGetFormMessagesByFormTO apiFormMessageGetFormMessagesByFormTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getFormMessagesByForm");
        System.out.println(apiFormMessageGetFormMessagesByFormTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiFormMessageTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiFormMessageTO>();
            com.wirelesscar.dynafleet.api.types.ApiFormMessageTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiFormMessageTO();
            com.wirelesscar.dynafleet.api.types.ApiFormId _returnArrayVal1FormId = new com.wirelesscar.dynafleet.api.types.ApiFormId();
            _returnArrayVal1FormId.setId(-195981767439570312l);
            _returnArrayVal1.setFormId(_returnArrayVal1FormId);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsRead = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsRead.setValue(true);
            _returnArrayVal1.setIsRead(_returnArrayVal1IsRead);
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiFormMessageFieldTO> _returnArrayVal1MessageData = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiFormMessageFieldTO>();
            _returnArrayVal1.getMessageData().addAll(_returnArrayVal1MessageData);
            com.wirelesscar.dynafleet.api.types.ApiFormMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiFormMessageId();
            _returnArrayVal1MessageId.setId(2947919007308071421l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            _returnArrayVal1.setSendstatus("Sendstatus613684639");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1SendstatusLastChangeTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1SendstatusLastChangeTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.591-05:00"));
            _returnArrayVal1.setSendstatusLastChangeTime(_returnArrayVal1SendstatusLastChangeTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.591-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnArrayVal1UserId = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnArrayVal1UserId.setId(Long.valueOf(-614030616255880242l));
            _returnArrayVal1.setUserId(_returnArrayVal1UserId);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(7308620039413740998l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#getDeletedFormMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiFormMessageIdArrayTO getDeletedFormMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDeletedFormMessages");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormMessageIdArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiFormMessageIdArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiFormMessageId> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiFormMessageId>();
            com.wirelesscar.dynafleet.api.types.ApiFormMessageId _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiFormMessageId();
            _returnArrayVal1.setId(1283855052871262193l);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#sendFormMessageWithDestinationPointToVehicle(com.wirelesscar.dynafleet.api.types.ApiFormMessageSendFormMessageWithDestinationPointToVehicleTO  apiFormMessageSendFormMessageWithDestinationPointToVehicleTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiFormMessageId sendFormMessageWithDestinationPointToVehicle(com.wirelesscar.dynafleet.api.types.ApiFormMessageSendFormMessageWithDestinationPointToVehicleTO apiFormMessageSendFormMessageWithDestinationPointToVehicleTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation sendFormMessageWithDestinationPointToVehicle");
        System.out.println(apiFormMessageSendFormMessageWithDestinationPointToVehicleTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormMessageId _return = new com.wirelesscar.dynafleet.api.types.ApiFormMessageId();
            _return.setId(-4109988889850883484l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#deleteFormMessages(com.wirelesscar.dynafleet.api.types.ApiFormMessageDeleteFormMessagesTO  apiFormMessageDeleteFormMessagesTO1 )*
     */
    public void deleteFormMessages(com.wirelesscar.dynafleet.api.types.ApiFormMessageDeleteFormMessagesTO apiFormMessageDeleteFormMessagesTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation deleteFormMessages");
        System.out.println(apiFormMessageDeleteFormMessagesTO1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#getNewFormMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO getNewFormMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewFormMessages");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiFormMessageTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiFormMessageTO>();
            com.wirelesscar.dynafleet.api.types.ApiFormMessageTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiFormMessageTO();
            com.wirelesscar.dynafleet.api.types.ApiFormId _returnArrayVal1FormId = new com.wirelesscar.dynafleet.api.types.ApiFormId();
            _returnArrayVal1FormId.setId(-2842147931951348442l);
            _returnArrayVal1.setFormId(_returnArrayVal1FormId);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsRead = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsRead.setValue(true);
            _returnArrayVal1.setIsRead(_returnArrayVal1IsRead);
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiFormMessageFieldTO> _returnArrayVal1MessageData = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiFormMessageFieldTO>();
            _returnArrayVal1.getMessageData().addAll(_returnArrayVal1MessageData);
            com.wirelesscar.dynafleet.api.types.ApiFormMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiFormMessageId();
            _returnArrayVal1MessageId.setId(-3970570651609572565l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            _returnArrayVal1.setSendstatus("Sendstatus2060406349");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1SendstatusLastChangeTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1SendstatusLastChangeTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.593-05:00"));
            _returnArrayVal1.setSendstatusLastChangeTime(_returnArrayVal1SendstatusLastChangeTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.593-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnArrayVal1UserId = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnArrayVal1UserId.setId(Long.valueOf(-4652031747400204367l));
            _returnArrayVal1.setUserId(_returnArrayVal1UserId);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(6728325789024208790l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#getNewFormMessageSendstatus(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiSendstatusArrayTO getNewFormMessageSendstatus(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewFormMessageSendstatus");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiSendstatusArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiSendstatusArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiSendstatusTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiSendstatusTO>();
            com.wirelesscar.dynafleet.api.types.ApiSendstatusTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiSendstatusTO();
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1ChangedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1ChangedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.594-05:00"));
            _returnArrayVal1.setChangedTime(_returnArrayVal1ChangedTime);
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1MessageId.setId(3786875930543018589l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            _returnArrayVal1.setSendstatus("Sendstatus-1846754217");
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#getFormMessagesInInbox(com.wirelesscar.dynafleet.api.types.ApiFormMessageGetFormMessagesInInboxTO  apiFormMessageGetFormMessagesInInboxTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO getFormMessagesInInbox(com.wirelesscar.dynafleet.api.types.ApiFormMessageGetFormMessagesInInboxTO apiFormMessageGetFormMessagesInInboxTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getFormMessagesInInbox");
        System.out.println(apiFormMessageGetFormMessagesInInboxTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiFormMessageArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiFormMessageTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiFormMessageTO>();
            com.wirelesscar.dynafleet.api.types.ApiFormMessageTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiFormMessageTO();
            com.wirelesscar.dynafleet.api.types.ApiFormId _returnArrayVal1FormId = new com.wirelesscar.dynafleet.api.types.ApiFormId();
            _returnArrayVal1FormId.setId(-5081383970982098402l);
            _returnArrayVal1.setFormId(_returnArrayVal1FormId);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsRead = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsRead.setValue(false);
            _returnArrayVal1.setIsRead(_returnArrayVal1IsRead);
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiFormMessageFieldTO> _returnArrayVal1MessageData = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiFormMessageFieldTO>();
            _returnArrayVal1.getMessageData().addAll(_returnArrayVal1MessageData);
            com.wirelesscar.dynafleet.api.types.ApiFormMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiFormMessageId();
            _returnArrayVal1MessageId.setId(-1638242771766777009l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            _returnArrayVal1.setSendstatus("Sendstatus-1428205717");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1SendstatusLastChangeTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1SendstatusLastChangeTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.595-05:00"));
            _returnArrayVal1.setSendstatusLastChangeTime(_returnArrayVal1SendstatusLastChangeTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.595-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnArrayVal1UserId = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnArrayVal1UserId.setId(Long.valueOf(-2467183195088403518l));
            _returnArrayVal1.setUserId(_returnArrayVal1UserId);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(6733770116533348224l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#sendFormMessageToVehicle(com.wirelesscar.dynafleet.api.types.ApiFormMessageSendFormMessageToVehicleTO  apiFormMessageSendFormMessageToVehicleTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiFormMessageId sendFormMessageToVehicle(com.wirelesscar.dynafleet.api.types.ApiFormMessageSendFormMessageToVehicleTO apiFormMessageSendFormMessageToVehicleTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation sendFormMessageToVehicle");
        System.out.println(apiFormMessageSendFormMessageToVehicleTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFormMessageId _return = new com.wirelesscar.dynafleet.api.types.ApiFormMessageId();
            _return.setId(2320203287799025157l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#deleteFormMessage(com.wirelesscar.dynafleet.api.types.ApiFormMessageDeleteFormMessageTO  apiFormMessageDeleteFormMessageTO1 )*
     */
    public void deleteFormMessage(com.wirelesscar.dynafleet.api.types.ApiFormMessageDeleteFormMessageTO apiFormMessageDeleteFormMessageTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation deleteFormMessage");
        System.out.println(apiFormMessageDeleteFormMessageTO1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.FormMessageService#getFormMessageReadAckInfos(com.wirelesscar.dynafleet.api.types.ApiFormMessageGetReadAckInfosTO  apiFormMessageGetReadAckInfosTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiReadAckInfoArrayTO getFormMessageReadAckInfos(com.wirelesscar.dynafleet.api.types.ApiFormMessageGetReadAckInfosTO apiFormMessageGetReadAckInfosTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getFormMessageReadAckInfos");
        System.out.println(apiFormMessageGetReadAckInfosTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiReadAckInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiReadAckInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO();
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1MessageId.setId(2597391664344111273l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1ReadAt = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1ReadAt.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.596-05:00"));
            _returnArrayVal1.setReadAt(_returnArrayVal1ReadAt);
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1ReadByDriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1ReadByDriverId.setId(-6118816745844259502l);
            _returnArrayVal1.setReadByDriverId(_returnArrayVal1ReadByDriverId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

}
