
package com.wirelesscar.dynafleet.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.309-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class GeofenceService_GeofenceServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://wirelesscar.com/dynafleet/api", "DynafleetAPI");

    private GeofenceService_GeofenceServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DynafleetAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DynafleetAPI ss = new DynafleetAPI(wsdlURL, SERVICE_NAME);
        GeofenceService port = ss.getGeofenceServicePort();  
        
        {
        System.out.println("Invoking getGeofences...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getGeofences_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getGeofences_apiSessionId1.setId("Id1626991227");
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofenceArrayTO _getGeofences__return = port.getGeofences(_getGeofences_apiSessionId1);
            System.out.println("getGeofences.result=" + _getGeofences__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking modifyGeofencePlus...");
        com.wirelesscar.dynafleet.api.types.ApiGeofencePlusCreateModifyTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1 = new com.wirelesscar.dynafleet.api.types.ApiGeofencePlusCreateModifyTO();
        com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details = new com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsTO();
        com.wirelesscar.dynafleet.api.types.ApiGeofenceActiveInformationTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation = new com.wirelesscar.dynafleet.api.types.ApiGeofenceActiveInformationTO();
        com.wirelesscar.dynafleet.api.types.ApiDate _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationEndTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationEndTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.319-05:00"));
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setEndTime(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationEndTime);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationFriday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationFriday.setValue(true);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setFriday(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationFriday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationMonday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationMonday.setValue(false);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setMonday(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationMonday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSaturday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSaturday.setValue(false);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setSaturday(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSaturday);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setSettingsType("SettingsType-107501740");
        com.wirelesscar.dynafleet.api.types.ApiDate _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationStartTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationStartTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.319-05:00"));
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setStartTime(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationStartTime);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSunday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSunday.setValue(false);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setSunday(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSunday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationThursday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationThursday.setValue(false);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setThursday(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationThursday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationTuesday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationTuesday.setValue(true);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setTuesday(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationTuesday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationWednesday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationWednesday.setValue(false);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setWednesday(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationWednesday);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setActiveInformation(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation);
        com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehicles = new com.wirelesscar.dynafleet.api.types.ApiLongArrayTO();
        java.util.List<com.wirelesscar.dynafleet.api.types.ApiLong> _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehiclesArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLong>();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehicles.getArray().addAll(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehiclesArray);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setAssignedVehicles(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehicles);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceBorderTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsBorder = new com.wirelesscar.dynafleet.api.types.ApiGeofenceBorderTO();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsBorder.setCountryCode("CountryCode180451306");
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setBorder(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsBorder);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceCircleTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle = new com.wirelesscar.dynafleet.api.types.ApiGeofenceCircleTO();
        com.wirelesscar.dynafleet.api.types.ApiPointTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLatitude.setValue(0.05632913951656138);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint.setLatitude(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLongitude.setValue(0.4515244375886879);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint.setLongitude(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLongitude);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle.setCenterPoint(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint);
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleRadius = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleRadius.setValue(0.6270155022677385);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle.setRadius(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleRadius);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setCircle(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setEnteringMessage("EnteringMessage1760901657");
        com.wirelesscar.dynafleet.api.types.ApiGeofenceId _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsGeofenceId = new com.wirelesscar.dynafleet.api.types.ApiGeofenceId();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsGeofenceId.setId(6260872320676362846l);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setGeofenceId(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsGeofenceId);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setGeofenceName("GeofenceName1528749095");
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setGeofenceType("GeofenceType-1599028009");
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setLeavingMessage("LeavingMessage2024362345");
        com.wirelesscar.dynafleet.api.types.ApiGeofencePoiTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi = new com.wirelesscar.dynafleet.api.types.ApiGeofencePoiTO();
        com.wirelesscar.dynafleet.api.types.ApiPoiId _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiPoiId = new com.wirelesscar.dynafleet.api.types.ApiPoiId();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiPoiId.setId(-2079570123678505434l);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi.setPoiId(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiPoiId);
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiRadius = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiRadius.setValue(0.5550950812518095);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi.setRadius(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiRadius);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setPoi(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi);
        com.wirelesscar.dynafleet.api.types.ApiGeofencePolygonTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygon = new com.wirelesscar.dynafleet.api.types.ApiGeofencePolygonTO();
        java.util.List<com.wirelesscar.dynafleet.api.types.ApiPointTO> _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygonPoints = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiPointTO>();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygon.getPoints().addAll(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygonPoints);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setPolygon(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygon);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceRectangleTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle = new com.wirelesscar.dynafleet.api.types.ApiGeofenceRectangleTO();
        com.wirelesscar.dynafleet.api.types.ApiPointTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELatitude.setValue(0.3096340574453449);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE.setLatitude(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELongitude.setValue(0.4320988050523128);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE.setLongitude(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELongitude);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle.setCornerNE(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE);
        com.wirelesscar.dynafleet.api.types.ApiPointTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLatitude.setValue(0.8333507288941954);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW.setLatitude(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLongitude.setValue(0.7425967596230192);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW.setLongitude(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLongitude);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle.setCornerSW(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setRectangle(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceRouteTO _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute = new com.wirelesscar.dynafleet.api.types.ApiGeofenceRouteTO();
        com.wirelesscar.dynafleet.api.types.ApiInteger _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteDeviation = new com.wirelesscar.dynafleet.api.types.ApiInteger();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteDeviation.setValue(709876603);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute.setDeviation(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteDeviation);
        java.util.List<com.wirelesscar.dynafleet.api.types.ApiPointTO> _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteWaypoints = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiPointTO>();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute.getWaypoints().addAll(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteWaypoints);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setRoute(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute);
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1.setDetails(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1Details);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1SessionId.setId("Id1811330127");
        _modifyGeofencePlus_apiGeofencePlusCreateModifyTO1.setSessionId(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofenceId _modifyGeofencePlus__return = port.modifyGeofencePlus(_modifyGeofencePlus_apiGeofencePlusCreateModifyTO1);
            System.out.println("modifyGeofencePlus.result=" + _modifyGeofencePlus__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getGeofencePlus...");
        com.wirelesscar.dynafleet.api.types.ApiGeofenceGetGeofenceTO _getGeofencePlus_apiGeofenceGetGeofenceTO1 = new com.wirelesscar.dynafleet.api.types.ApiGeofenceGetGeofenceTO();
        com.wirelesscar.dynafleet.api.types.ApiGeofenceId _getGeofencePlus_apiGeofenceGetGeofenceTO1GeofenceId = new com.wirelesscar.dynafleet.api.types.ApiGeofenceId();
        _getGeofencePlus_apiGeofenceGetGeofenceTO1GeofenceId.setId(3551231849251788532l);
        _getGeofencePlus_apiGeofenceGetGeofenceTO1.setGeofenceId(_getGeofencePlus_apiGeofenceGetGeofenceTO1GeofenceId);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getGeofencePlus_apiGeofenceGetGeofenceTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getGeofencePlus_apiGeofenceGetGeofenceTO1SessionId.setId("Id-1565982178");
        _getGeofencePlus_apiGeofenceGetGeofenceTO1.setSessionId(_getGeofencePlus_apiGeofenceGetGeofenceTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsTO _getGeofencePlus__return = port.getGeofencePlus(_getGeofencePlus_apiGeofenceGetGeofenceTO1);
            System.out.println("getGeofencePlus.result=" + _getGeofencePlus__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getGeofenceData...");
        com.wirelesscar.dynafleet.api.types.ApiGeofenceGetGeofenceDataTO _getGeofenceData_apiGeofenceGetGeofenceData = new com.wirelesscar.dynafleet.api.types.ApiGeofenceGetGeofenceDataTO();
        com.wirelesscar.dynafleet.api.types.ApiDate _getGeofenceData_apiGeofenceGetGeofenceDataFrom = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _getGeofenceData_apiGeofenceGetGeofenceDataFrom.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.322-05:00"));
        _getGeofenceData_apiGeofenceGetGeofenceData.setFrom(_getGeofenceData_apiGeofenceGetGeofenceDataFrom);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getGeofenceData_apiGeofenceGetGeofenceDataSessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getGeofenceData_apiGeofenceGetGeofenceDataSessionId.setId("Id-1373643600");
        _getGeofenceData_apiGeofenceGetGeofenceData.setSessionId(_getGeofenceData_apiGeofenceGetGeofenceDataSessionId);
        com.wirelesscar.dynafleet.api.types.ApiDate _getGeofenceData_apiGeofenceGetGeofenceDataTo = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _getGeofenceData_apiGeofenceGetGeofenceDataTo.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.322-05:00"));
        _getGeofenceData_apiGeofenceGetGeofenceData.setTo(_getGeofenceData_apiGeofenceGetGeofenceDataTo);
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofenceNotificationArrayTO _getGeofenceData__return = port.getGeofenceData(_getGeofenceData_apiGeofenceGetGeofenceData);
            System.out.println("getGeofenceData.result=" + _getGeofenceData__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getModifiedGeofencePlus...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getModifiedGeofencePlus_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getModifiedGeofencePlus_apiSessionId1.setId("Id1570720803");
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsArrayTO _getModifiedGeofencePlus__return = port.getModifiedGeofencePlus(_getModifiedGeofencePlus_apiSessionId1);
            System.out.println("getModifiedGeofencePlus.result=" + _getModifiedGeofencePlus__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createGeofencePlus...");
        com.wirelesscar.dynafleet.api.types.ApiGeofencePlusCreateModifyTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1 = new com.wirelesscar.dynafleet.api.types.ApiGeofencePlusCreateModifyTO();
        com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details = new com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsTO();
        com.wirelesscar.dynafleet.api.types.ApiGeofenceActiveInformationTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation = new com.wirelesscar.dynafleet.api.types.ApiGeofenceActiveInformationTO();
        com.wirelesscar.dynafleet.api.types.ApiDate _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationEndTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationEndTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.324-05:00"));
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setEndTime(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationEndTime);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationFriday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationFriday.setValue(true);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setFriday(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationFriday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationMonday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationMonday.setValue(false);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setMonday(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationMonday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSaturday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSaturday.setValue(false);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setSaturday(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSaturday);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setSettingsType("SettingsType-141986598");
        com.wirelesscar.dynafleet.api.types.ApiDate _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationStartTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationStartTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.324-05:00"));
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setStartTime(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationStartTime);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSunday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSunday.setValue(true);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setSunday(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationSunday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationThursday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationThursday.setValue(true);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setThursday(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationThursday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationTuesday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationTuesday.setValue(true);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setTuesday(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationTuesday);
        com.wirelesscar.dynafleet.api.types.ApiBoolean _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationWednesday = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationWednesday.setValue(false);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation.setWednesday(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformationWednesday);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setActiveInformation(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsActiveInformation);
        com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehicles = new com.wirelesscar.dynafleet.api.types.ApiLongArrayTO();
        java.util.List<com.wirelesscar.dynafleet.api.types.ApiLong> _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehiclesArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLong>();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehicles.getArray().addAll(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehiclesArray);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setAssignedVehicles(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsAssignedVehicles);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceBorderTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsBorder = new com.wirelesscar.dynafleet.api.types.ApiGeofenceBorderTO();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsBorder.setCountryCode("CountryCode-1642538116");
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setBorder(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsBorder);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceCircleTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle = new com.wirelesscar.dynafleet.api.types.ApiGeofenceCircleTO();
        com.wirelesscar.dynafleet.api.types.ApiPointTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLatitude.setValue(0.7219212920302422);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint.setLatitude(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLongitude.setValue(0.19055382233484008);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint.setLongitude(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPointLongitude);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle.setCenterPoint(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleCenterPoint);
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleRadius = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleRadius.setValue(0.11077440546576456);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle.setRadius(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircleRadius);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setCircle(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsCircle);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setEnteringMessage("EnteringMessage-2043569930");
        com.wirelesscar.dynafleet.api.types.ApiGeofenceId _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsGeofenceId = new com.wirelesscar.dynafleet.api.types.ApiGeofenceId();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsGeofenceId.setId(5645766199322963482l);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setGeofenceId(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsGeofenceId);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setGeofenceName("GeofenceName-389606408");
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setGeofenceType("GeofenceType-1706470021");
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setLeavingMessage("LeavingMessage1794323156");
        com.wirelesscar.dynafleet.api.types.ApiGeofencePoiTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi = new com.wirelesscar.dynafleet.api.types.ApiGeofencePoiTO();
        com.wirelesscar.dynafleet.api.types.ApiPoiId _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiPoiId = new com.wirelesscar.dynafleet.api.types.ApiPoiId();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiPoiId.setId(8950187746543851169l);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi.setPoiId(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiPoiId);
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiRadius = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiRadius.setValue(0.9060722296022077);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi.setRadius(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoiRadius);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setPoi(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPoi);
        com.wirelesscar.dynafleet.api.types.ApiGeofencePolygonTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygon = new com.wirelesscar.dynafleet.api.types.ApiGeofencePolygonTO();
        java.util.List<com.wirelesscar.dynafleet.api.types.ApiPointTO> _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygonPoints = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiPointTO>();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygon.getPoints().addAll(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygonPoints);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setPolygon(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsPolygon);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceRectangleTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle = new com.wirelesscar.dynafleet.api.types.ApiGeofenceRectangleTO();
        com.wirelesscar.dynafleet.api.types.ApiPointTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELatitude.setValue(0.21889098739412693);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE.setLatitude(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELongitude.setValue(0.7002243786850245);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE.setLongitude(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNELongitude);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle.setCornerNE(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerNE);
        com.wirelesscar.dynafleet.api.types.ApiPointTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLatitude.setValue(0.26443454881056816);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW.setLatitude(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLongitude.setValue(0.8105305212880339);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW.setLongitude(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSWLongitude);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle.setCornerSW(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangleCornerSW);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setRectangle(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRectangle);
        com.wirelesscar.dynafleet.api.types.ApiGeofenceRouteTO _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute = new com.wirelesscar.dynafleet.api.types.ApiGeofenceRouteTO();
        com.wirelesscar.dynafleet.api.types.ApiInteger _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteDeviation = new com.wirelesscar.dynafleet.api.types.ApiInteger();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteDeviation.setValue(-1737210197);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute.setDeviation(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteDeviation);
        java.util.List<com.wirelesscar.dynafleet.api.types.ApiPointTO> _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteWaypoints = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiPointTO>();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute.getWaypoints().addAll(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRouteWaypoints);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1Details.setRoute(_createGeofencePlus_apiGeofencePlusCreateModifyTO1DetailsRoute);
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1.setDetails(_createGeofencePlus_apiGeofencePlusCreateModifyTO1Details);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _createGeofencePlus_apiGeofencePlusCreateModifyTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1SessionId.setId("Id-1693442065");
        _createGeofencePlus_apiGeofencePlusCreateModifyTO1.setSessionId(_createGeofencePlus_apiGeofencePlusCreateModifyTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofenceId _createGeofencePlus__return = port.createGeofencePlus(_createGeofencePlus_apiGeofencePlusCreateModifyTO1);
            System.out.println("createGeofencePlus.result=" + _createGeofencePlus__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNewGeofenceData...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getNewGeofenceData_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getNewGeofenceData_apiSessionId1.setId("Id117334357");
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofenceNotificationArrayTO _getNewGeofenceData__return = port.getNewGeofenceData(_getNewGeofenceData_apiSessionId1);
            System.out.println("getNewGeofenceData.result=" + _getNewGeofenceData__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getNewGeofencePlusData...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getNewGeofencePlusData_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getNewGeofencePlusData_apiSessionId1.setId("Id743297103");
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofencePlusNotificationArrayTO _getNewGeofencePlusData__return = port.getNewGeofencePlusData(_getNewGeofencePlusData_apiSessionId1);
            System.out.println("getNewGeofencePlusData.result=" + _getNewGeofencePlusData__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDeletedGeofencePlus...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getDeletedGeofencePlus_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getDeletedGeofencePlus_apiSessionId1.setId("Id-1167012804");
        try {
            com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsArrayTO _getDeletedGeofencePlus__return = port.getDeletedGeofencePlus(_getDeletedGeofencePlus_apiSessionId1);
            System.out.println("getDeletedGeofencePlus.result=" + _getDeletedGeofencePlus__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
