package com.wirelesscar.dynafleet.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.653-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wirelesscar.com/dynafleet/api", name = "GeofenceService")
@XmlSeeAlso({com.wirelesscar.dynafleet.api.types.ObjectFactory.class})
public interface GeofenceService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getGeofences", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetGeofences")
    @WebMethod
    @ResponseWrapper(localName = "getGeofencesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetGeofencesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofenceArrayTO getGeofences(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "modifyGeofencePlus", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.ModifyGeofencePlus")
    @WebMethod
    @ResponseWrapper(localName = "modifyGeofencePlusResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.ModifyGeofencePlusResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofenceId modifyGeofencePlus(
        @WebParam(name = "Api_GeofencePlusCreateModifyTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiGeofencePlusCreateModifyTO apiGeofencePlusCreateModifyTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getGeofencePlus", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetGeofencePlus")
    @WebMethod
    @ResponseWrapper(localName = "getGeofencePlusResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetGeofencePlusResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsTO getGeofencePlus(
        @WebParam(name = "Api_GeofenceGetGeofenceTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiGeofenceGetGeofenceTO apiGeofenceGetGeofenceTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getGeofenceData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetGeofenceData")
    @WebMethod
    @ResponseWrapper(localName = "getGeofenceDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetGeofenceDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofenceNotificationArrayTO getGeofenceData(
        @WebParam(name = "Api_GeofenceGetGeofenceData", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiGeofenceGetGeofenceDataTO apiGeofenceGetGeofenceData
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getModifiedGeofencePlus", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedGeofencePlus")
    @WebMethod
    @ResponseWrapper(localName = "getModifiedGeofencePlusResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedGeofencePlusResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsArrayTO getModifiedGeofencePlus(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createGeofencePlus", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.CreateGeofencePlus")
    @WebMethod
    @ResponseWrapper(localName = "createGeofencePlusResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.CreateGeofencePlusResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofenceId createGeofencePlus(
        @WebParam(name = "Api_GeofencePlusCreateModifyTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiGeofencePlusCreateModifyTO apiGeofencePlusCreateModifyTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewGeofenceData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewGeofenceData")
    @WebMethod
    @ResponseWrapper(localName = "getNewGeofenceDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewGeofenceDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofenceNotificationArrayTO getNewGeofenceData(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewGeofencePlusData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewGeofencePlusData")
    @WebMethod
    @ResponseWrapper(localName = "getNewGeofencePlusDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewGeofencePlusDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofencePlusNotificationArrayTO getNewGeofencePlusData(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeletedGeofencePlus", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedGeofencePlus")
    @WebMethod
    @ResponseWrapper(localName = "getDeletedGeofencePlusResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedGeofencePlusResponse")
    public com.wirelesscar.dynafleet.api.types.ApiGeofencePlusDetailsArrayTO getDeletedGeofencePlus(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;
}
