
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wirelesscar.dynafleet.api;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.484-05:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "DynafleetAPI",
                      portName = "MessageServicePort",
                      targetNamespace = "http://wirelesscar.com/dynafleet/api",
                      wsdlLocation = "https://api-preprod.dynafleetonline.com/wsdl",
                      endpointInterface = "com.wirelesscar.dynafleet.api.MessageService")
                      
public class MessageServiceImpl implements MessageService {

    private static final Logger LOG = Logger.getLogger(MessageServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getNewVehicleEventMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO getNewVehicleEventMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewVehicleEventMessages");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO>();
            com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO();
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1VehicleEventMessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1VehicleEventMessageId.setId(5688131914274619206l);
            _returnArrayVal1.setVehicleEventMessageId(_returnArrayVal1VehicleEventMessageId);
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(-229571985573663492l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(-7638339137617044940l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArrayVal1.setTrigger("Trigger1578798211");
            com.wirelesscar.dynafleet.api.types.ApiVehicleEventId _returnArrayVal1VehicleEventId = new com.wirelesscar.dynafleet.api.types.ApiVehicleEventId();
            _returnArrayVal1VehicleEventId.setId(5838068266575004401l);
            _returnArrayVal1.setVehicleEventId(_returnArrayVal1VehicleEventId);
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1Position = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionAltitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionAltitude.setValue(0.029020891819168892);
            _returnArrayVal1Position.setAltitude(_returnArrayVal1PositionAltitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1PositionHeading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1PositionHeading.setValue(0.6365859f);
            _returnArrayVal1Position.setHeading(_returnArrayVal1PositionHeading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLatitude.setValue(0.08031249583044764);
            _returnArrayVal1Position.setLatitude(_returnArrayVal1PositionLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLongitude.setValue(0.1354707296020894);
            _returnArrayVal1Position.setLongitude(_returnArrayVal1PositionLongitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionPositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionPositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.491-05:00"));
            _returnArrayVal1Position.setPositionTime(_returnArrayVal1PositionPositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.491-05:00"));
            _returnArrayVal1Position.setReceivedTime(_returnArrayVal1PositionReceivedTime);
            _returnArrayVal1.setPosition(_returnArrayVal1Position);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.492-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsRead = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsRead.setValue(false);
            _returnArrayVal1.setIsRead(_returnArrayVal1IsRead);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1FuelLevelChangePercent = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1FuelLevelChangePercent.setValue(0.042262018f);
            _returnArrayVal1.setFuelLevelChangePercent(_returnArrayVal1FuelLevelChangePercent);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1CurrentFuelLevelPercent = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1CurrentFuelLevelPercent.setValue(0.06238532f);
            _returnArrayVal1.setCurrentFuelLevelPercent(_returnArrayVal1CurrentFuelLevelPercent);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AdBlueLevelChangeMm = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AdBlueLevelChangeMm.setValue(4912500306531907119l);
            _returnArrayVal1.setAdBlueLevelChangeMm(_returnArrayVal1AdBlueLevelChangeMm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AdBlueLevelChangePerMille = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AdBlueLevelChangePerMille.setValue(-4578031588907699364l);
            _returnArrayVal1.setAdBlueLevelChangePerMille(_returnArrayVal1AdBlueLevelChangePerMille);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoDoorStatus = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoDoorStatus.setValue(true);
            _returnArrayVal1.setCargoDoorStatus(_returnArrayVal1CargoDoorStatus);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoDefrostStatus = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoDefrostStatus.setValue(true);
            _returnArrayVal1.setCargoDefrostStatus(_returnArrayVal1CargoDefrostStatus);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature1Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature1Alarm.setValue(false);
            _returnArrayVal1.setCargoTemperature1Alarm(_returnArrayVal1CargoTemperature1Alarm);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature2Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature2Alarm.setValue(false);
            _returnArrayVal1.setCargoTemperature2Alarm(_returnArrayVal1CargoTemperature2Alarm);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature3Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature3Alarm.setValue(false);
            _returnArrayVal1.setCargoTemperature3Alarm(_returnArrayVal1CargoTemperature3Alarm);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature4Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature4Alarm.setValue(true);
            _returnArrayVal1.setCargoTemperature4Alarm(_returnArrayVal1CargoTemperature4Alarm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature1 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature1.setValue(-4692082046601348407l);
            _returnArrayVal1.setCargoTemperature1(_returnArrayVal1CargoTemperature1);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature2 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature2.setValue(4010203319569187548l);
            _returnArrayVal1.setCargoTemperature2(_returnArrayVal1CargoTemperature2);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature3 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature3.setValue(6135917346757837526l);
            _returnArrayVal1.setCargoTemperature3(_returnArrayVal1CargoTemperature3);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature4 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature4.setValue(7215164897015867265l);
            _returnArrayVal1.setCargoTemperature4(_returnArrayVal1CargoTemperature4);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getNewAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO getNewAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewAlarms");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiAlarmTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiAlarmTO>();
            com.wirelesscar.dynafleet.api.types.ApiAlarmTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiAlarmTO();
            com.wirelesscar.dynafleet.api.types.ApiAlarmId _returnArrayVal1AlarmId = new com.wirelesscar.dynafleet.api.types.ApiAlarmId();
            _returnArrayVal1AlarmId.setId(Long.valueOf(-4134814771374043603l));
            _returnArrayVal1.setAlarmId(_returnArrayVal1AlarmId);
            _returnArrayVal1.setAlarmStatus("AlarmStatus-1430338010");
            _returnArrayVal1.setAlarmType("AlarmType-214048861");
            _returnArrayVal1.setDriverLanguageCode("DriverLanguageCode1780712984");
            _returnArrayVal1.setDriverName("DriverName2032441712");
            _returnArrayVal1.setDriverPhoneNumber("DriverPhoneNumber769968276");
            _returnArrayVal1.setMessageData("MessageData-1837553925");
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1Position = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionAltitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionAltitude.setValue(0.56495526753754);
            _returnArrayVal1Position.setAltitude(_returnArrayVal1PositionAltitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1PositionHeading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1PositionHeading.setValue(0.52195853f);
            _returnArrayVal1Position.setHeading(_returnArrayVal1PositionHeading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLatitude.setValue(0.5680541203103869);
            _returnArrayVal1Position.setLatitude(_returnArrayVal1PositionLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLongitude.setValue(0.024881167255930925);
            _returnArrayVal1Position.setLongitude(_returnArrayVal1PositionLongitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionPositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionPositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.493-05:00"));
            _returnArrayVal1Position.setPositionTime(_returnArrayVal1PositionPositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.494-05:00"));
            _returnArrayVal1Position.setReceivedTime(_returnArrayVal1PositionReceivedTime);
            _returnArrayVal1.setPosition(_returnArrayVal1Position);
            _returnArrayVal1.setSendStatus("SendStatus1518987378");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1SendStatusChangedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1SendStatusChangedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.494-05:00"));
            _returnArrayVal1.setSendStatusChangedTime(_returnArrayVal1SendStatusChangedTime);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1Sender = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1Sender.setId(-4491189703706371690l);
            _returnArrayVal1.setSender(_returnArrayVal1Sender);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.494-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#sendMessageWithDestinationPointToVehicle(com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageWithDestinationPointToVehicleTO  apiMessageSendMessageWithDestinationPointToVehicleTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiMessageId sendMessageWithDestinationPointToVehicle(com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageWithDestinationPointToVehicleTO apiMessageSendMessageWithDestinationPointToVehicleTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation sendMessageWithDestinationPointToVehicle");
        System.out.println(apiMessageSendMessageWithDestinationPointToVehicleTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiMessageId _return = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _return.setId(8295173074075454870l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getMessagesInInbox(com.wirelesscar.dynafleet.api.types.ApiMessageGetMessagesInInboxTO  apiMessageGetMessagesInInboxTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO getMessagesInInbox(com.wirelesscar.dynafleet.api.types.ApiMessageGetMessagesInInboxTO apiMessageGetMessagesInInboxTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getMessagesInInbox");
        System.out.println(apiMessageGetMessagesInInboxTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiMessageTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiMessageTO>();
            com.wirelesscar.dynafleet.api.types.ApiMessageTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiMessageTO();
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnArrayVal1FromUserId = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnArrayVal1FromUserId.setId(Long.valueOf(4883568525582368786l));
            _returnArrayVal1.setFromUserId(_returnArrayVal1FromUserId);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1FromVehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1FromVehicleId.setId(-517523682606934337l);
            _returnArrayVal1.setFromVehicleId(_returnArrayVal1FromVehicleId);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsRead = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsRead.setValue(false);
            _returnArrayVal1.setIsRead(_returnArrayVal1IsRead);
            _returnArrayVal1.setMessageData("MessageData-762396909");
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1MessageId.setId(4310213122936567699l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.496-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getDeletedMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiMessageIdArrayTO getDeletedMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDeletedMessages");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiMessageIdArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiMessageIdArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiMessageId> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiMessageId>();
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1.setId(-5342700122413255466l);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getDeletedAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiAlarmIdArrayTO getDeletedAlarms(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDeletedAlarms");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiAlarmIdArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiAlarmIdArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiAlarmId> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiAlarmId>();
            com.wirelesscar.dynafleet.api.types.ApiAlarmId _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiAlarmId();
            _returnArrayVal1.setId(Long.valueOf(-4243476450297007426l));
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getMessageReadAckInfos(com.wirelesscar.dynafleet.api.types.ApiMessageGetReadAckInfosTO  apiMessageGetReadAckInfosTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiReadAckInfoArrayTO getMessageReadAckInfos(com.wirelesscar.dynafleet.api.types.ApiMessageGetReadAckInfosTO apiMessageGetReadAckInfosTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getMessageReadAckInfos");
        System.out.println(apiMessageGetReadAckInfosTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiReadAckInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiReadAckInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiReadAckInfoTO();
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1MessageId.setId(6391398379681561720l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1ReadAt = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1ReadAt.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.498-05:00"));
            _returnArrayVal1.setReadAt(_returnArrayVal1ReadAt);
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1ReadByDriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1ReadByDriverId.setId(8967925036082420282l);
            _returnArrayVal1.setReadByDriverId(_returnArrayVal1ReadByDriverId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#sendMessageToUser(com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageToUserTO  apiMessageSendMessageToUserTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiMessageId sendMessageToUser(com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageToUserTO apiMessageSendMessageToUserTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation sendMessageToUser");
        System.out.println(apiMessageSendMessageToUserTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiMessageId _return = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _return.setId(-6171335899263176224l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#sendMessageToVehicle(com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageToVehicleTO  apiMessageSendMessageToVehicleTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiMessageId sendMessageToVehicle(com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageToVehicleTO apiMessageSendMessageToVehicleTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation sendMessageToVehicle");
        System.out.println(apiMessageSendMessageToVehicleTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiMessageId _return = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _return.setId(3326511136583503825l);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getVehicleEventMessages(com.wirelesscar.dynafleet.api.types.ApiMessageGetVehicleEventMessagesTO  apiMessageGetVehicleEventMessages1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO getVehicleEventMessages(com.wirelesscar.dynafleet.api.types.ApiMessageGetVehicleEventMessagesTO apiMessageGetVehicleEventMessages1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getVehicleEventMessages");
        System.out.println(apiMessageGetVehicleEventMessages1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO>();
            com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageTO();
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1VehicleEventMessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1VehicleEventMessageId.setId(5243849269832273883l);
            _returnArrayVal1.setVehicleEventMessageId(_returnArrayVal1VehicleEventMessageId);
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(-8582808604354147873l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(-3529896003562697593l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            _returnArrayVal1.setTrigger("Trigger-408754935");
            com.wirelesscar.dynafleet.api.types.ApiVehicleEventId _returnArrayVal1VehicleEventId = new com.wirelesscar.dynafleet.api.types.ApiVehicleEventId();
            _returnArrayVal1VehicleEventId.setId(5544740778724416897l);
            _returnArrayVal1.setVehicleEventId(_returnArrayVal1VehicleEventId);
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1Position = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionAltitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionAltitude.setValue(0.014440048852705556);
            _returnArrayVal1Position.setAltitude(_returnArrayVal1PositionAltitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1PositionHeading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1PositionHeading.setValue(0.059732795f);
            _returnArrayVal1Position.setHeading(_returnArrayVal1PositionHeading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLatitude.setValue(0.924308500941124);
            _returnArrayVal1Position.setLatitude(_returnArrayVal1PositionLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLongitude.setValue(0.3597212715216236);
            _returnArrayVal1Position.setLongitude(_returnArrayVal1PositionLongitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionPositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionPositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.499-05:00"));
            _returnArrayVal1Position.setPositionTime(_returnArrayVal1PositionPositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.499-05:00"));
            _returnArrayVal1Position.setReceivedTime(_returnArrayVal1PositionReceivedTime);
            _returnArrayVal1.setPosition(_returnArrayVal1Position);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.500-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsRead = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsRead.setValue(true);
            _returnArrayVal1.setIsRead(_returnArrayVal1IsRead);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1FuelLevelChangePercent = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1FuelLevelChangePercent.setValue(0.3650477f);
            _returnArrayVal1.setFuelLevelChangePercent(_returnArrayVal1FuelLevelChangePercent);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1CurrentFuelLevelPercent = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1CurrentFuelLevelPercent.setValue(0.64311814f);
            _returnArrayVal1.setCurrentFuelLevelPercent(_returnArrayVal1CurrentFuelLevelPercent);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AdBlueLevelChangeMm = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AdBlueLevelChangeMm.setValue(-2752334599614431583l);
            _returnArrayVal1.setAdBlueLevelChangeMm(_returnArrayVal1AdBlueLevelChangeMm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AdBlueLevelChangePerMille = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AdBlueLevelChangePerMille.setValue(7046245582475684124l);
            _returnArrayVal1.setAdBlueLevelChangePerMille(_returnArrayVal1AdBlueLevelChangePerMille);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoDoorStatus = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoDoorStatus.setValue(true);
            _returnArrayVal1.setCargoDoorStatus(_returnArrayVal1CargoDoorStatus);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoDefrostStatus = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoDefrostStatus.setValue(false);
            _returnArrayVal1.setCargoDefrostStatus(_returnArrayVal1CargoDefrostStatus);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature1Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature1Alarm.setValue(true);
            _returnArrayVal1.setCargoTemperature1Alarm(_returnArrayVal1CargoTemperature1Alarm);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature2Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature2Alarm.setValue(true);
            _returnArrayVal1.setCargoTemperature2Alarm(_returnArrayVal1CargoTemperature2Alarm);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature3Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature3Alarm.setValue(false);
            _returnArrayVal1.setCargoTemperature3Alarm(_returnArrayVal1CargoTemperature3Alarm);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature4Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature4Alarm.setValue(false);
            _returnArrayVal1.setCargoTemperature4Alarm(_returnArrayVal1CargoTemperature4Alarm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature1 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature1.setValue(8125951686605119574l);
            _returnArrayVal1.setCargoTemperature1(_returnArrayVal1CargoTemperature1);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature2 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature2.setValue(-5053365873930128117l);
            _returnArrayVal1.setCargoTemperature2(_returnArrayVal1CargoTemperature2);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature3 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature3.setValue(-4298558358888602549l);
            _returnArrayVal1.setCargoTemperature3(_returnArrayVal1CargoTemperature3);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature4 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature4.setValue(-3652391082529393463l);
            _returnArrayVal1.setCargoTemperature4(_returnArrayVal1CargoTemperature4);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#setAutoDeleteMessage(com.wirelesscar.dynafleet.api.types.ApiMessageSetAutoDeleteMessageTO  apiMessageSetAutoDeleteMessageTO1 )*
     */
    public void setAutoDeleteMessage(com.wirelesscar.dynafleet.api.types.ApiMessageSetAutoDeleteMessageTO apiMessageSetAutoDeleteMessageTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation setAutoDeleteMessage");
        System.out.println(apiMessageSetAutoDeleteMessageTO1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#deleteMessagesByTimestamp(com.wirelesscar.dynafleet.api.types.ApiMessageDeleteMessagesByTimestampTO  apiMessageDeleteMessagesByTimestampTO1 )*
     */
    public void deleteMessagesByTimestamp(com.wirelesscar.dynafleet.api.types.ApiMessageDeleteMessagesByTimestampTO apiMessageDeleteMessagesByTimestampTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation deleteMessagesByTimestamp");
        System.out.println(apiMessageDeleteMessagesByTimestampTO1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getNewMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO getNewMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewMessages");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiMessageTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiMessageTO>();
            com.wirelesscar.dynafleet.api.types.ApiMessageTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiMessageTO();
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnArrayVal1FromUserId = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnArrayVal1FromUserId.setId(Long.valueOf(-1540919492520669796l));
            _returnArrayVal1.setFromUserId(_returnArrayVal1FromUserId);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1FromVehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1FromVehicleId.setId(-9093455163210540566l);
            _returnArrayVal1.setFromVehicleId(_returnArrayVal1FromVehicleId);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1IsRead = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1IsRead.setValue(true);
            _returnArrayVal1.setIsRead(_returnArrayVal1IsRead);
            _returnArrayVal1.setMessageData("MessageData-1028332220");
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1MessageId.setId(6320048836272938903l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.502-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#deleteMessage(com.wirelesscar.dynafleet.api.types.ApiMessageDeleteMessageTO  apiMessageDeleteMessageTO1 )*
     */
    public void deleteMessage(com.wirelesscar.dynafleet.api.types.ApiMessageDeleteMessageTO apiMessageDeleteMessageTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation deleteMessage");
        System.out.println(apiMessageDeleteMessageTO1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getAlarms(com.wirelesscar.dynafleet.api.types.ApiAlarmGetAlarmsTO  apiAlarmGetAlarmsTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO getAlarms(com.wirelesscar.dynafleet.api.types.ApiAlarmGetAlarmsTO apiAlarmGetAlarmsTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getAlarms");
        System.out.println(apiAlarmGetAlarmsTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiAlarmTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiAlarmTO>();
            com.wirelesscar.dynafleet.api.types.ApiAlarmTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiAlarmTO();
            com.wirelesscar.dynafleet.api.types.ApiAlarmId _returnArrayVal1AlarmId = new com.wirelesscar.dynafleet.api.types.ApiAlarmId();
            _returnArrayVal1AlarmId.setId(Long.valueOf(-809883259875145576l));
            _returnArrayVal1.setAlarmId(_returnArrayVal1AlarmId);
            _returnArrayVal1.setAlarmStatus("AlarmStatus-243573482");
            _returnArrayVal1.setAlarmType("AlarmType-1282288108");
            _returnArrayVal1.setDriverLanguageCode("DriverLanguageCode92296838");
            _returnArrayVal1.setDriverName("DriverName664063384");
            _returnArrayVal1.setDriverPhoneNumber("DriverPhoneNumber277392695");
            _returnArrayVal1.setMessageData("MessageData618778934");
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1Position = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionAltitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionAltitude.setValue(0.01467852672450265);
            _returnArrayVal1Position.setAltitude(_returnArrayVal1PositionAltitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1PositionHeading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1PositionHeading.setValue(0.5174439f);
            _returnArrayVal1Position.setHeading(_returnArrayVal1PositionHeading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLatitude.setValue(0.2992788561555839);
            _returnArrayVal1Position.setLatitude(_returnArrayVal1PositionLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLongitude.setValue(0.872668654066212);
            _returnArrayVal1Position.setLongitude(_returnArrayVal1PositionLongitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionPositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionPositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.503-05:00"));
            _returnArrayVal1Position.setPositionTime(_returnArrayVal1PositionPositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.503-05:00"));
            _returnArrayVal1Position.setReceivedTime(_returnArrayVal1PositionReceivedTime);
            _returnArrayVal1.setPosition(_returnArrayVal1Position);
            _returnArrayVal1.setSendStatus("SendStatus-1892866058");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1SendStatusChangedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1SendStatusChangedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.503-05:00"));
            _returnArrayVal1.setSendStatusChangedTime(_returnArrayVal1SendStatusChangedTime);
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1Sender = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1Sender.setId(1312494027920413370l);
            _returnArrayVal1.setSender(_returnArrayVal1Sender);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.504-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#getNewMessagesSendstatus(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiSendstatusArrayTO getNewMessagesSendstatus(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewMessagesSendstatus");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiSendstatusArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiSendstatusArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiSendstatusTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiSendstatusTO>();
            com.wirelesscar.dynafleet.api.types.ApiSendstatusTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiSendstatusTO();
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1ChangedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1ChangedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.505-05:00"));
            _returnArrayVal1.setChangedTime(_returnArrayVal1ChangedTime);
            com.wirelesscar.dynafleet.api.types.ApiMessageId _returnArrayVal1MessageId = new com.wirelesscar.dynafleet.api.types.ApiMessageId();
            _returnArrayVal1MessageId.setId(5084351615580972189l);
            _returnArrayVal1.setMessageId(_returnArrayVal1MessageId);
            _returnArrayVal1.setSendstatus("Sendstatus282466143");
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.MessageService#deleteReadMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public void deleteReadMessages(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation deleteReadMessages");
        System.out.println(apiSessionId1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

}
