package com.wirelesscar.dynafleet.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.649-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wirelesscar.com/dynafleet/api", name = "MessageService")
@XmlSeeAlso({com.wirelesscar.dynafleet.api.types.ObjectFactory.class})
public interface MessageService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewVehicleEventMessages", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewVehicleEventMessages")
    @WebMethod
    @ResponseWrapper(localName = "getNewVehicleEventMessagesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewVehicleEventMessagesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO getNewVehicleEventMessages(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewAlarms", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewAlarms")
    @WebMethod
    @ResponseWrapper(localName = "getNewAlarmsResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewAlarmsResponse")
    public com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO getNewAlarms(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendMessageWithDestinationPointToVehicle", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SendMessageWithDestinationPointToVehicle")
    @WebMethod
    @ResponseWrapper(localName = "sendMessageWithDestinationPointToVehicleResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SendMessageWithDestinationPointToVehicleResponse")
    public com.wirelesscar.dynafleet.api.types.ApiMessageId sendMessageWithDestinationPointToVehicle(
        @WebParam(name = "Api_MessageSendMessageWithDestinationPointToVehicleTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageWithDestinationPointToVehicleTO apiMessageSendMessageWithDestinationPointToVehicleTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getMessagesInInbox", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetMessagesInInbox")
    @WebMethod
    @ResponseWrapper(localName = "getMessagesInInboxResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetMessagesInInboxResponse")
    public com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO getMessagesInInbox(
        @WebParam(name = "Api_MessageGetMessagesInInboxTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageGetMessagesInInboxTO apiMessageGetMessagesInInboxTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeletedMessages", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedMessages")
    @WebMethod
    @ResponseWrapper(localName = "getDeletedMessagesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedMessagesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiMessageIdArrayTO getDeletedMessages(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeletedAlarms", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedAlarms")
    @WebMethod
    @ResponseWrapper(localName = "getDeletedAlarmsResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedAlarmsResponse")
    public com.wirelesscar.dynafleet.api.types.ApiAlarmIdArrayTO getDeletedAlarms(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getMessageReadAckInfos", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetMessageReadAckInfos")
    @WebMethod
    @ResponseWrapper(localName = "getMessageReadAckInfosResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetMessageReadAckInfosResponse")
    public com.wirelesscar.dynafleet.api.types.ApiReadAckInfoArrayTO getMessageReadAckInfos(
        @WebParam(name = "Api_MessageGetReadAckInfosTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageGetReadAckInfosTO apiMessageGetReadAckInfosTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendMessageToUser", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SendMessageToUser")
    @WebMethod
    @ResponseWrapper(localName = "sendMessageToUserResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SendMessageToUserResponse")
    public com.wirelesscar.dynafleet.api.types.ApiMessageId sendMessageToUser(
        @WebParam(name = "Api_MessageSendMessageToUserTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageToUserTO apiMessageSendMessageToUserTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "sendMessageToVehicle", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SendMessageToVehicle")
    @WebMethod
    @ResponseWrapper(localName = "sendMessageToVehicleResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SendMessageToVehicleResponse")
    public com.wirelesscar.dynafleet.api.types.ApiMessageId sendMessageToVehicle(
        @WebParam(name = "Api_MessageSendMessageToVehicleTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageSendMessageToVehicleTO apiMessageSendMessageToVehicleTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleEventMessages", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicleEventMessages")
    @WebMethod
    @ResponseWrapper(localName = "getVehicleEventMessagesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicleEventMessagesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleEventMessageArrayTO getVehicleEventMessages(
        @WebParam(name = "Api_MessageGetVehicleEventMessages_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageGetVehicleEventMessagesTO apiMessageGetVehicleEventMessages1
    ) throws DynafleetAPIException;

    @RequestWrapper(localName = "setAutoDeleteMessage", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SetAutoDeleteMessage")
    @WebMethod
    @ResponseWrapper(localName = "setAutoDeleteMessageResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.SetAutoDeleteMessageResponse")
    public void setAutoDeleteMessage(
        @WebParam(name = "Api_MessageSetAutoDeleteMessageTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageSetAutoDeleteMessageTO apiMessageSetAutoDeleteMessageTO1
    ) throws DynafleetAPIException;

    @RequestWrapper(localName = "deleteMessagesByTimestamp", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeleteMessagesByTimestamp")
    @WebMethod
    @ResponseWrapper(localName = "deleteMessagesByTimestampResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeleteMessagesByTimestampResponse")
    public void deleteMessagesByTimestamp(
        @WebParam(name = "Api_MessageDeleteMessagesByTimestampTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageDeleteMessagesByTimestampTO apiMessageDeleteMessagesByTimestampTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewMessages", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewMessages")
    @WebMethod
    @ResponseWrapper(localName = "getNewMessagesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewMessagesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiMessageArrayTO getNewMessages(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @RequestWrapper(localName = "deleteMessage", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeleteMessage")
    @WebMethod
    @ResponseWrapper(localName = "deleteMessageResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeleteMessageResponse")
    public void deleteMessage(
        @WebParam(name = "Api_MessageDeleteMessageTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiMessageDeleteMessageTO apiMessageDeleteMessageTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getAlarms", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetAlarms")
    @WebMethod
    @ResponseWrapper(localName = "getAlarmsResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetAlarmsResponse")
    public com.wirelesscar.dynafleet.api.types.ApiAlarmArrayTO getAlarms(
        @WebParam(name = "Api_AlarmGetAlarmsTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiAlarmGetAlarmsTO apiAlarmGetAlarmsTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewMessagesSendstatus", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewMessagesSendstatus")
    @WebMethod
    @ResponseWrapper(localName = "getNewMessagesSendstatusResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewMessagesSendstatusResponse")
    public com.wirelesscar.dynafleet.api.types.ApiSendstatusArrayTO getNewMessagesSendstatus(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @RequestWrapper(localName = "deleteReadMessages", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeleteReadMessages")
    @WebMethod
    @ResponseWrapper(localName = "deleteReadMessagesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeleteReadMessagesResponse")
    public void deleteReadMessages(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;
}
