
package com.wirelesscar.dynafleet.api;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.349-05:00
 * Generated source version: 2.7.18
 * 
 */
public final class PoiService_PoiServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://wirelesscar.com/dynafleet/api", "DynafleetAPI");

    private PoiService_PoiServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DynafleetAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DynafleetAPI ss = new DynafleetAPI(wsdlURL, SERVICE_NAME);
        PoiService port = ss.getPoiServicePort();  
        
        {
        System.out.println("Invoking modifyPoi...");
        com.wirelesscar.dynafleet.api.types.ApiPoiModifyPoiTO _modifyPoi_apiPoiModifyPoiTO1 = new com.wirelesscar.dynafleet.api.types.ApiPoiModifyPoiTO();
        com.wirelesscar.dynafleet.api.types.ApiPoiTO _modifyPoi_apiPoiModifyPoiTO1Poi = new com.wirelesscar.dynafleet.api.types.ApiPoiTO();
        com.wirelesscar.dynafleet.api.types.ApiLong _modifyPoi_apiPoiModifyPoiTO1PoiCategory = new com.wirelesscar.dynafleet.api.types.ApiLong();
        _modifyPoi_apiPoiModifyPoiTO1PoiCategory.setValue(3031527664787625863l);
        _modifyPoi_apiPoiModifyPoiTO1Poi.setCategory(_modifyPoi_apiPoiModifyPoiTO1PoiCategory);
        _modifyPoi_apiPoiModifyPoiTO1Poi.setCity("City-1482608708");
        _modifyPoi_apiPoiModifyPoiTO1Poi.setCountry("Country2088229066");
        com.wirelesscar.dynafleet.api.types.ApiDate _modifyPoi_apiPoiModifyPoiTO1PoiCreateTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _modifyPoi_apiPoiModifyPoiTO1PoiCreateTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.357-05:00"));
        _modifyPoi_apiPoiModifyPoiTO1Poi.setCreateTime(_modifyPoi_apiPoiModifyPoiTO1PoiCreateTime);
        com.wirelesscar.dynafleet.api.types.ApiDate _modifyPoi_apiPoiModifyPoiTO1PoiDeletedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _modifyPoi_apiPoiModifyPoiTO1PoiDeletedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.357-05:00"));
        _modifyPoi_apiPoiModifyPoiTO1Poi.setDeletedTime(_modifyPoi_apiPoiModifyPoiTO1PoiDeletedTime);
        _modifyPoi_apiPoiModifyPoiTO1Poi.setDescription("Description-2124453353");
        _modifyPoi_apiPoiModifyPoiTO1Poi.setDisplayName("DisplayName1883374261");
        com.wirelesscar.dynafleet.api.types.ApiDate _modifyPoi_apiPoiModifyPoiTO1PoiLastModifyTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _modifyPoi_apiPoiModifyPoiTO1PoiLastModifyTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.358-05:00"));
        _modifyPoi_apiPoiModifyPoiTO1Poi.setLastModifyTime(_modifyPoi_apiPoiModifyPoiTO1PoiLastModifyTime);
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyPoi_apiPoiModifyPoiTO1PoiLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyPoi_apiPoiModifyPoiTO1PoiLatitude.setValue(0.2624607307361866);
        _modifyPoi_apiPoiModifyPoiTO1Poi.setLatitude(_modifyPoi_apiPoiModifyPoiTO1PoiLatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _modifyPoi_apiPoiModifyPoiTO1PoiLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _modifyPoi_apiPoiModifyPoiTO1PoiLongitude.setValue(0.8332748789942096);
        _modifyPoi_apiPoiModifyPoiTO1Poi.setLongitude(_modifyPoi_apiPoiModifyPoiTO1PoiLongitude);
        com.wirelesscar.dynafleet.api.types.ApiPoiId _modifyPoi_apiPoiModifyPoiTO1PoiPoiId = new com.wirelesscar.dynafleet.api.types.ApiPoiId();
        _modifyPoi_apiPoiModifyPoiTO1PoiPoiId.setId(1189081067517914876l);
        _modifyPoi_apiPoiModifyPoiTO1Poi.setPoiId(_modifyPoi_apiPoiModifyPoiTO1PoiPoiId);
        _modifyPoi_apiPoiModifyPoiTO1Poi.setStreet("Street589206942");
        _modifyPoi_apiPoiModifyPoiTO1.setPoi(_modifyPoi_apiPoiModifyPoiTO1Poi);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _modifyPoi_apiPoiModifyPoiTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _modifyPoi_apiPoiModifyPoiTO1SessionId.setId("Id-909011301");
        _modifyPoi_apiPoiModifyPoiTO1.setSessionId(_modifyPoi_apiPoiModifyPoiTO1SessionId);
        try {
            port.modifyPoi(_modifyPoi_apiPoiModifyPoiTO1);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getDeletedPois...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getDeletedPois_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getDeletedPois_apiSessionId1.setId("Id637990723");
        try {
            com.wirelesscar.dynafleet.api.types.ApiPoiIdArrayTO _getDeletedPois__return = port.getDeletedPois(_getDeletedPois_apiSessionId1);
            System.out.println("getDeletedPois.result=" + _getDeletedPois__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deletePoi...");
        com.wirelesscar.dynafleet.api.types.ApiPoiDeletePoiTO _deletePoi_apiPoiDeletePoiTO1 = new com.wirelesscar.dynafleet.api.types.ApiPoiDeletePoiTO();
        com.wirelesscar.dynafleet.api.types.ApiPoiId _deletePoi_apiPoiDeletePoiTO1PoiId = new com.wirelesscar.dynafleet.api.types.ApiPoiId();
        _deletePoi_apiPoiDeletePoiTO1PoiId.setId(-1228398525108106763l);
        _deletePoi_apiPoiDeletePoiTO1.setPoiId(_deletePoi_apiPoiDeletePoiTO1PoiId);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _deletePoi_apiPoiDeletePoiTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _deletePoi_apiPoiDeletePoiTO1SessionId.setId("Id847151053");
        _deletePoi_apiPoiDeletePoiTO1.setSessionId(_deletePoi_apiPoiDeletePoiTO1SessionId);
        try {
            port.deletePoi(_deletePoi_apiPoiDeletePoiTO1);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createPoi...");
        com.wirelesscar.dynafleet.api.types.ApiPoiCreatePoiTO _createPoi_apiPoiCreatePoiTO1 = new com.wirelesscar.dynafleet.api.types.ApiPoiCreatePoiTO();
        com.wirelesscar.dynafleet.api.types.ApiPoiTO _createPoi_apiPoiCreatePoiTO1Poi = new com.wirelesscar.dynafleet.api.types.ApiPoiTO();
        com.wirelesscar.dynafleet.api.types.ApiLong _createPoi_apiPoiCreatePoiTO1PoiCategory = new com.wirelesscar.dynafleet.api.types.ApiLong();
        _createPoi_apiPoiCreatePoiTO1PoiCategory.setValue(6668239057649213402l);
        _createPoi_apiPoiCreatePoiTO1Poi.setCategory(_createPoi_apiPoiCreatePoiTO1PoiCategory);
        _createPoi_apiPoiCreatePoiTO1Poi.setCity("City899149432");
        _createPoi_apiPoiCreatePoiTO1Poi.setCountry("Country-1484968103");
        com.wirelesscar.dynafleet.api.types.ApiDate _createPoi_apiPoiCreatePoiTO1PoiCreateTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _createPoi_apiPoiCreatePoiTO1PoiCreateTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.359-05:00"));
        _createPoi_apiPoiCreatePoiTO1Poi.setCreateTime(_createPoi_apiPoiCreatePoiTO1PoiCreateTime);
        com.wirelesscar.dynafleet.api.types.ApiDate _createPoi_apiPoiCreatePoiTO1PoiDeletedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _createPoi_apiPoiCreatePoiTO1PoiDeletedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.360-05:00"));
        _createPoi_apiPoiCreatePoiTO1Poi.setDeletedTime(_createPoi_apiPoiCreatePoiTO1PoiDeletedTime);
        _createPoi_apiPoiCreatePoiTO1Poi.setDescription("Description871073264");
        _createPoi_apiPoiCreatePoiTO1Poi.setDisplayName("DisplayName1954476076");
        com.wirelesscar.dynafleet.api.types.ApiDate _createPoi_apiPoiCreatePoiTO1PoiLastModifyTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
        _createPoi_apiPoiCreatePoiTO1PoiLastModifyTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.360-05:00"));
        _createPoi_apiPoiCreatePoiTO1Poi.setLastModifyTime(_createPoi_apiPoiCreatePoiTO1PoiLastModifyTime);
        com.wirelesscar.dynafleet.api.types.ApiDouble _createPoi_apiPoiCreatePoiTO1PoiLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createPoi_apiPoiCreatePoiTO1PoiLatitude.setValue(0.37118761834412217);
        _createPoi_apiPoiCreatePoiTO1Poi.setLatitude(_createPoi_apiPoiCreatePoiTO1PoiLatitude);
        com.wirelesscar.dynafleet.api.types.ApiDouble _createPoi_apiPoiCreatePoiTO1PoiLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _createPoi_apiPoiCreatePoiTO1PoiLongitude.setValue(0.15600821905274143);
        _createPoi_apiPoiCreatePoiTO1Poi.setLongitude(_createPoi_apiPoiCreatePoiTO1PoiLongitude);
        com.wirelesscar.dynafleet.api.types.ApiPoiId _createPoi_apiPoiCreatePoiTO1PoiPoiId = new com.wirelesscar.dynafleet.api.types.ApiPoiId();
        _createPoi_apiPoiCreatePoiTO1PoiPoiId.setId(-243412719329608583l);
        _createPoi_apiPoiCreatePoiTO1Poi.setPoiId(_createPoi_apiPoiCreatePoiTO1PoiPoiId);
        _createPoi_apiPoiCreatePoiTO1Poi.setStreet("Street1368770873");
        _createPoi_apiPoiCreatePoiTO1.setPoi(_createPoi_apiPoiCreatePoiTO1Poi);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _createPoi_apiPoiCreatePoiTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _createPoi_apiPoiCreatePoiTO1SessionId.setId("Id-697880778");
        _createPoi_apiPoiCreatePoiTO1.setSessionId(_createPoi_apiPoiCreatePoiTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiLong _createPoi__return = port.createPoi(_createPoi_apiPoiCreatePoiTO1);
            System.out.println("createPoi.result=" + _createPoi__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPoisByBoundingBox...");
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByBoundingBoxTO _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1 = new com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByBoundingBoxTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Latitude1 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Latitude1.setValue(0.5883720894223782);
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1.setLatitude1(_getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Latitude1);
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Latitude2 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Latitude2.setValue(0.3347521564162822);
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1.setLatitude2(_getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Latitude2);
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Longitude1 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Longitude1.setValue(0.8569355670952293);
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1.setLongitude1(_getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Longitude1);
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Longitude2 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Longitude2.setValue(0.653383448788631);
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1.setLongitude2(_getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1Longitude2);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1SessionId.setId("Id-1994984889");
        _getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1.setSessionId(_getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO _getPoisByBoundingBox__return = port.getPoisByBoundingBox(_getPoisByBoundingBox_apiPoiGetPoisByBoundingBoxTO1);
            System.out.println("getPoisByBoundingBox.result=" + _getPoisByBoundingBox__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPoisByTypeAndBoundingBox...");
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByTypeAndBoundingBoxTO _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1 = new com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByTypeAndBoundingBoxTO();
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Latitude1 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Latitude1.setValue(0.8062084799800214);
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1.setLatitude1(_getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Latitude1);
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Latitude2 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Latitude2.setValue(0.45553445492343236);
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1.setLatitude2(_getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Latitude2);
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Longitude1 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Longitude1.setValue(0.03375499122322334);
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1.setLongitude1(_getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Longitude1);
        com.wirelesscar.dynafleet.api.types.ApiDouble _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Longitude2 = new com.wirelesscar.dynafleet.api.types.ApiDouble();
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Longitude2.setValue(0.273825510043028);
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1.setLongitude2(_getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1Longitude2);
        com.wirelesscar.dynafleet.api.types.ApiLong _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1PoiType = new com.wirelesscar.dynafleet.api.types.ApiLong();
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1PoiType.setValue(5539663291522344650l);
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1.setPoiType(_getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1PoiType);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1SessionId.setId("Id-1336033623");
        _getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1.setSessionId(_getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO _getPoisByTypeAndBoundingBox__return = port.getPoisByTypeAndBoundingBox(_getPoisByTypeAndBoundingBox_apiPoiGetPoisByTypeAndBoundingBoxTO1);
            System.out.println("getPoisByTypeAndBoundingBox.result=" + _getPoisByTypeAndBoundingBox__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getModifiedPois...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getModifiedPois_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getModifiedPois_apiSessionId1.setId("Id-65030102");
        try {
            com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO _getModifiedPois__return = port.getModifiedPois(_getModifiedPois_apiSessionId1);
            System.out.println("getModifiedPois.result=" + _getModifiedPois__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPoisByType...");
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByTypeTO _getPoisByType_apiPoiGetPoisByTypeTO1 = new com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByTypeTO();
        com.wirelesscar.dynafleet.api.types.ApiLong _getPoisByType_apiPoiGetPoisByTypeTO1PoiType = new com.wirelesscar.dynafleet.api.types.ApiLong();
        _getPoisByType_apiPoiGetPoisByTypeTO1PoiType.setValue(-6264010917365390384l);
        _getPoisByType_apiPoiGetPoisByTypeTO1.setPoiType(_getPoisByType_apiPoiGetPoisByTypeTO1PoiType);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getPoisByType_apiPoiGetPoisByTypeTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getPoisByType_apiPoiGetPoisByTypeTO1SessionId.setId("Id1428124510");
        _getPoisByType_apiPoiGetPoisByTypeTO1.setSessionId(_getPoisByType_apiPoiGetPoisByTypeTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO _getPoisByType__return = port.getPoisByType(_getPoisByType_apiPoiGetPoisByTypeTO1);
            System.out.println("getPoisByType.result=" + _getPoisByType__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPoi...");
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoiTO _getPoi_apiPoiGetPoiTO1 = new com.wirelesscar.dynafleet.api.types.ApiPoiGetPoiTO();
        com.wirelesscar.dynafleet.api.types.ApiPoiId _getPoi_apiPoiGetPoiTO1PoiId = new com.wirelesscar.dynafleet.api.types.ApiPoiId();
        _getPoi_apiPoiGetPoiTO1PoiId.setId(1811562603795856300l);
        _getPoi_apiPoiGetPoiTO1.setPoiId(_getPoi_apiPoiGetPoiTO1PoiId);
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getPoi_apiPoiGetPoiTO1SessionId = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getPoi_apiPoiGetPoiTO1SessionId.setId("Id818131534");
        _getPoi_apiPoiGetPoiTO1.setSessionId(_getPoi_apiPoiGetPoiTO1SessionId);
        try {
            com.wirelesscar.dynafleet.api.types.ApiPoiTO _getPoi__return = port.getPoi(_getPoi_apiPoiGetPoiTO1);
            System.out.println("getPoi.result=" + _getPoi__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPois...");
        com.wirelesscar.dynafleet.api.types.ApiSessionId _getPois_apiSessionId1 = new com.wirelesscar.dynafleet.api.types.ApiSessionId();
        _getPois_apiSessionId1.setId("Id-2118432261");
        try {
            com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO _getPois__return = port.getPois(_getPois_apiSessionId1);
            System.out.println("getPois.result=" + _getPois__return);

        } catch (DynafleetAPIException e) { 
            System.out.println("Expected exception: DynafleetAPIException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
