package com.wirelesscar.dynafleet.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.659-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wirelesscar.com/dynafleet/api", name = "PoiService")
@XmlSeeAlso({com.wirelesscar.dynafleet.api.types.ObjectFactory.class})
public interface PoiService {

    @RequestWrapper(localName = "modifyPoi", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.ModifyPoi")
    @WebMethod
    @ResponseWrapper(localName = "modifyPoiResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.ModifyPoiResponse")
    public void modifyPoi(
        @WebParam(name = "Api_PoiModifyPoiTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiPoiModifyPoiTO apiPoiModifyPoiTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeletedPois", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedPois")
    @WebMethod
    @ResponseWrapper(localName = "getDeletedPoisResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedPoisResponse")
    public com.wirelesscar.dynafleet.api.types.ApiPoiIdArrayTO getDeletedPois(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @RequestWrapper(localName = "deletePoi", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeletePoi")
    @WebMethod
    @ResponseWrapper(localName = "deletePoiResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.DeletePoiResponse")
    public void deletePoi(
        @WebParam(name = "Api_PoiDeletePoiTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiPoiDeletePoiTO apiPoiDeletePoiTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "createPoi", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.CreatePoi")
    @WebMethod
    @ResponseWrapper(localName = "createPoiResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.CreatePoiResponse")
    public com.wirelesscar.dynafleet.api.types.ApiLong createPoi(
        @WebParam(name = "Api_PoiCreatePoiTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiPoiCreatePoiTO apiPoiCreatePoiTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getPoisByBoundingBox", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoisByBoundingBox")
    @WebMethod
    @ResponseWrapper(localName = "getPoisByBoundingBoxResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoisByBoundingBoxResponse")
    public com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO getPoisByBoundingBox(
        @WebParam(name = "Api_PoiGetPoisByBoundingBoxTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByBoundingBoxTO apiPoiGetPoisByBoundingBoxTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getPoisByTypeAndBoundingBox", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoisByTypeAndBoundingBox")
    @WebMethod
    @ResponseWrapper(localName = "getPoisByTypeAndBoundingBoxResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoisByTypeAndBoundingBoxResponse")
    public com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO getPoisByTypeAndBoundingBox(
        @WebParam(name = "Api_PoiGetPoisByTypeAndBoundingBoxTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByTypeAndBoundingBoxTO apiPoiGetPoisByTypeAndBoundingBoxTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getModifiedPois", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedPois")
    @WebMethod
    @ResponseWrapper(localName = "getModifiedPoisResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedPoisResponse")
    public com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO getModifiedPois(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getPoisByType", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoisByType")
    @WebMethod
    @ResponseWrapper(localName = "getPoisByTypeResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoisByTypeResponse")
    public com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO getPoisByType(
        @WebParam(name = "Api_PoiGetPoisByTypeTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoisByTypeTO apiPoiGetPoisByTypeTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getPoi", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoi")
    @WebMethod
    @ResponseWrapper(localName = "getPoiResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoiResponse")
    public com.wirelesscar.dynafleet.api.types.ApiPoiTO getPoi(
        @WebParam(name = "Api_PoiGetPoiTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiPoiGetPoiTO apiPoiGetPoiTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getPois", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPois")
    @WebMethod
    @ResponseWrapper(localName = "getPoisResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetPoisResponse")
    public com.wirelesscar.dynafleet.api.types.ApiPoiArrayTO getPois(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;
}
