package com.wirelesscar.dynafleet.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.682-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wirelesscar.com/dynafleet/api", name = "ReportService")
@XmlSeeAlso({com.wirelesscar.dynafleet.api.types.ObjectFactory.class})
public interface ReportService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewVehicleReportDataExtended", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewVehicleReportDataExtended")
    @WebMethod
    @ResponseWrapper(localName = "getNewVehicleReportDataExtendedResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewVehicleReportDataExtendedResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleDataExtendedArrayTO getNewVehicleReportDataExtended(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewVehicleReportData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewVehicleReportData")
    @WebMethod
    @ResponseWrapper(localName = "getNewVehicleReportDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewVehicleReportDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleDataArrayTO getNewVehicleReportData(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewDriverReportData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewDriverReportData")
    @WebMethod
    @ResponseWrapper(localName = "getNewDriverReportDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewDriverReportDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDriverDataArrayTO getNewDriverReportData(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleReportData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicleReportData")
    @WebMethod
    @ResponseWrapper(localName = "getVehicleReportDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicleReportDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleDataTO getVehicleReportData(
        @WebParam(name = "Api_ReportGetVehicleReportDataTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiReportGetVehicleReportDataTO apiReportGetVehicleReportDataTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getNewDtjReportData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewDtjReportData")
    @WebMethod
    @ResponseWrapper(localName = "getNewDtjReportDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetNewDtjReportDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDtjDataArrayTO getNewDtjReportData(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDtjReportData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDtjReportData")
    @WebMethod
    @ResponseWrapper(localName = "getDtjReportDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDtjReportDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDtjDataTO getDtjReportData(
        @WebParam(name = "Api_GetDtjActivitiesTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiGetDtjActivitiesTO apiGetDtjActivitiesTO1
    ) throws DynafleetAPIException;

    @RequestWrapper(localName = "makeManualDownload", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.MakeManualDownload")
    @WebMethod
    @ResponseWrapper(localName = "makeManualDownloadResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.MakeManualDownloadResponse")
    public void makeManualDownload(
        @WebParam(name = "Api_ReportMakeManualDownloadTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiReportMakeManualDownloadTO apiReportMakeManualDownloadTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDriverReportData", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriverReportData")
    @WebMethod
    @ResponseWrapper(localName = "getDriverReportDataResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriverReportDataResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDriverDataTO getDriverReportData(
        @WebParam(name = "Api_ReportGetDriverReportDataTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiReportGetDriverReportDataTO apiReportGetDriverReportDataTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVehicleReportDataExtended", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicleReportDataExtended")
    @WebMethod
    @ResponseWrapper(localName = "getVehicleReportDataExtendedResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicleReportDataExtendedResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleDataExtendedTO getVehicleReportDataExtended(
        @WebParam(name = "Api_ReportGetVehicleReportDataTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiReportGetVehicleReportDataTO apiReportGetVehicleReportDataTO1
    ) throws DynafleetAPIException;
}
