
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wirelesscar.dynafleet.api;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.574-05:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "DynafleetAPI",
                      portName = "TrackingServicePort",
                      targetNamespace = "http://wirelesscar.com/dynafleet/api",
                      wsdlLocation = "https://api-preprod.dynafleetonline.com/wsdl",
                      endpointInterface = "com.wirelesscar.dynafleet.api.TrackingService")
                      
public class TrackingServiceImpl implements TrackingService {

    private static final Logger LOG = Logger.getLogger(TrackingServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.TrackingService#getLastKnownPositions(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiLastKnownPositionArrayTO getLastKnownPositions(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getLastKnownPositions");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiLastKnownPositionArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiLastKnownPositionArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiLastKnownPositionTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLastKnownPositionTO>();
            com.wirelesscar.dynafleet.api.types.ApiLastKnownPositionTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiLastKnownPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(2865093502154803732l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionDateTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionDateTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.578-05:00"));
            _returnArrayVal1.setPositionDateTime(_returnArrayVal1PositionDateTime);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Latitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Latitude.setValue(0.3620500615666026);
            _returnArrayVal1.setLatitude(_returnArrayVal1Latitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Longitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Longitude.setValue(0.8766575220572543);
            _returnArrayVal1.setLongitude(_returnArrayVal1Longitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Altitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Altitude.setValue(0.11764436746520535);
            _returnArrayVal1.setAltitude(_returnArrayVal1Altitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1Heading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1Heading.setValue(0.7243388f);
            _returnArrayVal1.setHeading(_returnArrayVal1Heading);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.TrackingService#getNewPositions(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiPositionPlusArrayTO getNewPositions(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewPositions");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiPositionPlusArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiPositionPlusArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiPositionPlusTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiPositionPlusTO>();
            com.wirelesscar.dynafleet.api.types.ApiPositionPlusTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiPositionPlusTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Latitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Latitude.setValue(0.8433268836760238);
            _returnArrayVal1.setLatitude(_returnArrayVal1Latitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Longitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Longitude.setValue(0.6170140902776151);
            _returnArrayVal1.setLongitude(_returnArrayVal1Longitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.579-05:00"));
            _returnArrayVal1.setPositionTime(_returnArrayVal1PositionTime);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1VehicleInformationId = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1VehicleInformationId.setValue(-3099467198181890193l);
            _returnArrayVal1.setVehicleInformationId(_returnArrayVal1VehicleInformationId);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.TrackingService#getNewTrackingData(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiTrackingDataArrayTO getNewTrackingData(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewTrackingData");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiTrackingDataArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiTrackingDataArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiTrackingDataTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiTrackingDataTO>();
            com.wirelesscar.dynafleet.api.types.ApiTrackingDataTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiTrackingDataTO();
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AccumulatedFuelConsumption = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AccumulatedFuelConsumption.setValue(-3712201251507983791l);
            _returnArrayVal1.setAccumulatedFuelConsumption(_returnArrayVal1AccumulatedFuelConsumption);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature1 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature1.setValue(-1497250179389331692l);
            _returnArrayVal1.setCargoTemperature1(_returnArrayVal1CargoTemperature1);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature2 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature2.setValue(7172135490746460281l);
            _returnArrayVal1.setCargoTemperature2(_returnArrayVal1CargoTemperature2);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature3 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature3.setValue(4594652400883268764l);
            _returnArrayVal1.setCargoTemperature3(_returnArrayVal1CargoTemperature3);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature4 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature4.setValue(7484383422244701985l);
            _returnArrayVal1.setCargoTemperature4(_returnArrayVal1CargoTemperature4);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature5 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature5.setValue(5838747886932574132l);
            _returnArrayVal1.setCargoTemperature5(_returnArrayVal1CargoTemperature5);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature6 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature6.setValue(-2486259587796837623l);
            _returnArrayVal1.setCargoTemperature6(_returnArrayVal1CargoTemperature6);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature7 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature7.setValue(704860604084088006l);
            _returnArrayVal1.setCargoTemperature7(_returnArrayVal1CargoTemperature7);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature8 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature8.setValue(-2299120441349391614l);
            _returnArrayVal1.setCargoTemperature8(_returnArrayVal1CargoTemperature8);
            _returnArrayVal1.setCurrentDriverActivity("CurrentDriverActivity558713540");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(-7971846101867054838l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1DrivingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1DrivingTime.setValue(-2809640525631048559l);
            _returnArrayVal1.setDrivingTime(_returnArrayVal1DrivingTime);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1FrontAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1FrontAxleWeight.setValue(-4773145009811613782l);
            _returnArrayVal1.setFrontAxleWeight(_returnArrayVal1FrontAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1MomentaneousVehicleSpeed = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1MomentaneousVehicleSpeed.setValue(8559153081091967492l);
            _returnArrayVal1.setMomentaneousVehicleSpeed(_returnArrayVal1MomentaneousVehicleSpeed);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1Odometer = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1Odometer.setValue(-6373837006098737544l);
            _returnArrayVal1.setOdometer(_returnArrayVal1Odometer);
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1Position = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionAltitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionAltitude.setValue(0.6392175638521467);
            _returnArrayVal1Position.setAltitude(_returnArrayVal1PositionAltitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1PositionHeading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1PositionHeading.setValue(0.41493028f);
            _returnArrayVal1Position.setHeading(_returnArrayVal1PositionHeading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLatitude.setValue(0.6786821632107991);
            _returnArrayVal1Position.setLatitude(_returnArrayVal1PositionLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLongitude.setValue(0.735508107053932);
            _returnArrayVal1Position.setLongitude(_returnArrayVal1PositionLongitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionPositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionPositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.580-05:00"));
            _returnArrayVal1Position.setPositionTime(_returnArrayVal1PositionPositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.580-05:00"));
            _returnArrayVal1Position.setReceivedTime(_returnArrayVal1PositionReceivedTime);
            _returnArrayVal1.setPosition(_returnArrayVal1Position);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RearAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RearAxleWeight.setValue(-1859903426823860034l);
            _returnArrayVal1.setRearAxleWeight(_returnArrayVal1RearAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RestingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RestingTime.setValue(952289895559217540l);
            _returnArrayVal1.setRestingTime(_returnArrayVal1RestingTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.580-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TotalWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TotalWeight.setValue(6672362541780405254l);
            _returnArrayVal1.setTotalWeight(_returnArrayVal1TotalWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerFrontAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerFrontAxleWeight.setValue(-2199641192654978812l);
            _returnArrayVal1.setTrailerFrontAxleWeight(_returnArrayVal1TrailerFrontAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerRearAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerRearAxleWeight.setValue(-2685375223125265558l);
            _returnArrayVal1.setTrailerRearAxleWeight(_returnArrayVal1TrailerRearAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerTotalWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerTotalWeight.setValue(7146544434204050439l);
            _returnArrayVal1.setTrailerTotalWeight(_returnArrayVal1TrailerTotalWeight);
            _returnArrayVal1.setTriggerType("TriggerType-1621407813");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(-6767719070654113759l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1WaitingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1WaitingTime.setValue(-5797449512820361085l);
            _returnArrayVal1.setWaitingTime(_returnArrayVal1WaitingTime);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1WorkingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1WorkingTime.setValue(3936561043102626824l);
            _returnArrayVal1.setWorkingTime(_returnArrayVal1WorkingTime);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.TrackingService#getVehiclePositions(com.wirelesscar.dynafleet.api.types.ApiTrackingGetVehiclePositionTO  apiTrackingGetVehiclePositionTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiPositionArrayTO getVehiclePositions(com.wirelesscar.dynafleet.api.types.ApiTrackingGetVehiclePositionTO apiTrackingGetVehiclePositionTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getVehiclePositions");
        System.out.println(apiTrackingGetVehiclePositionTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiPositionArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiPositionArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiPositionTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiPositionTO>();
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Altitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Altitude.setValue(0.8637488221263332);
            _returnArrayVal1.setAltitude(_returnArrayVal1Altitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1Heading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1Heading.setValue(0.71625465f);
            _returnArrayVal1.setHeading(_returnArrayVal1Heading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Latitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Latitude.setValue(0.07429533115035747);
            _returnArrayVal1.setLatitude(_returnArrayVal1Latitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1Longitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1Longitude.setValue(0.056844001730685156);
            _returnArrayVal1.setLongitude(_returnArrayVal1Longitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.581-05:00"));
            _returnArrayVal1.setPositionTime(_returnArrayVal1PositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1ReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1ReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.582-05:00"));
            _returnArrayVal1.setReceivedTime(_returnArrayVal1ReceivedTime);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.TrackingService#getNewTrackingDataWithETAInfo(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiTrackingDataWithETAInfoArrayTO getNewTrackingDataWithETAInfo(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewTrackingDataWithETAInfo");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiTrackingDataWithETAInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiTrackingDataWithETAInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiTrackingDataWithETAInfoTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiTrackingDataWithETAInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiTrackingDataWithETAInfoTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiTrackingDataWithETAInfoTO();
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AccumulatedFuelConsumption = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AccumulatedFuelConsumption.setValue(4423939310338870307l);
            _returnArrayVal1.setAccumulatedFuelConsumption(_returnArrayVal1AccumulatedFuelConsumption);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature1 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature1.setValue(-7038309172159522423l);
            _returnArrayVal1.setCargoTemperature1(_returnArrayVal1CargoTemperature1);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature2 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature2.setValue(2983607241287439040l);
            _returnArrayVal1.setCargoTemperature2(_returnArrayVal1CargoTemperature2);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature3 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature3.setValue(-2901597891522420154l);
            _returnArrayVal1.setCargoTemperature3(_returnArrayVal1CargoTemperature3);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature4 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature4.setValue(-1347121723117400998l);
            _returnArrayVal1.setCargoTemperature4(_returnArrayVal1CargoTemperature4);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature5 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature5.setValue(-4725155622117604921l);
            _returnArrayVal1.setCargoTemperature5(_returnArrayVal1CargoTemperature5);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature6 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature6.setValue(2654879204775976963l);
            _returnArrayVal1.setCargoTemperature6(_returnArrayVal1CargoTemperature6);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature7 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature7.setValue(-5323113661537647408l);
            _returnArrayVal1.setCargoTemperature7(_returnArrayVal1CargoTemperature7);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature8 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature8.setValue(4529624995291294663l);
            _returnArrayVal1.setCargoTemperature8(_returnArrayVal1CargoTemperature8);
            _returnArrayVal1.setCurrentDriverActivity("CurrentDriverActivity-147301428");
            com.wirelesscar.dynafleet.api.types.ApiPointTO _returnArrayVal1DestinationPoint = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1DestinationPointLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1DestinationPointLatitude.setValue(0.0526918465345072);
            _returnArrayVal1DestinationPoint.setLatitude(_returnArrayVal1DestinationPointLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1DestinationPointLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1DestinationPointLongitude.setValue(0.6065685671408707);
            _returnArrayVal1DestinationPoint.setLongitude(_returnArrayVal1DestinationPointLongitude);
            _returnArrayVal1.setDestinationPoint(_returnArrayVal1DestinationPoint);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1DistanceToDestination = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1DistanceToDestination.setValue(-3389509552556986709l);
            _returnArrayVal1.setDistanceToDestination(_returnArrayVal1DistanceToDestination);
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(3962607487456505841l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1DrivingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1DrivingTime.setValue(6083823392311722055l);
            _returnArrayVal1.setDrivingTime(_returnArrayVal1DrivingTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1EtaTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1EtaTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.583-05:00"));
            _returnArrayVal1.setEtaTime(_returnArrayVal1EtaTime);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1FrontAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1FrontAxleWeight.setValue(9148318352772345823l);
            _returnArrayVal1.setFrontAxleWeight(_returnArrayVal1FrontAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1MomentaneousVehicleSpeed = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1MomentaneousVehicleSpeed.setValue(3783843060818640127l);
            _returnArrayVal1.setMomentaneousVehicleSpeed(_returnArrayVal1MomentaneousVehicleSpeed);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1Odometer = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1Odometer.setValue(-7813350985858010730l);
            _returnArrayVal1.setOdometer(_returnArrayVal1Odometer);
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1Position = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionAltitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionAltitude.setValue(0.28701515419420764);
            _returnArrayVal1Position.setAltitude(_returnArrayVal1PositionAltitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1PositionHeading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1PositionHeading.setValue(0.45314765f);
            _returnArrayVal1Position.setHeading(_returnArrayVal1PositionHeading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLatitude.setValue(0.13243902564403376);
            _returnArrayVal1Position.setLatitude(_returnArrayVal1PositionLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLongitude.setValue(0.8938411430562291);
            _returnArrayVal1Position.setLongitude(_returnArrayVal1PositionLongitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionPositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionPositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.583-05:00"));
            _returnArrayVal1Position.setPositionTime(_returnArrayVal1PositionPositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.583-05:00"));
            _returnArrayVal1Position.setReceivedTime(_returnArrayVal1PositionReceivedTime);
            _returnArrayVal1.setPosition(_returnArrayVal1Position);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RearAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RearAxleWeight.setValue(-4112780322118464149l);
            _returnArrayVal1.setRearAxleWeight(_returnArrayVal1RearAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RestingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RestingTime.setValue(2662547032037317879l);
            _returnArrayVal1.setRestingTime(_returnArrayVal1RestingTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.584-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TotalWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TotalWeight.setValue(6479188202117397698l);
            _returnArrayVal1.setTotalWeight(_returnArrayVal1TotalWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerFrontAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerFrontAxleWeight.setValue(-5660392739868729138l);
            _returnArrayVal1.setTrailerFrontAxleWeight(_returnArrayVal1TrailerFrontAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerRearAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerRearAxleWeight.setValue(-4968192225676285356l);
            _returnArrayVal1.setTrailerRearAxleWeight(_returnArrayVal1TrailerRearAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerTotalWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerTotalWeight.setValue(-3267006908435360220l);
            _returnArrayVal1.setTrailerTotalWeight(_returnArrayVal1TrailerTotalWeight);
            _returnArrayVal1.setTriggerType("TriggerType-554266127");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(1314824798427212898l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1WaitingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1WaitingTime.setValue(-1460211277599769838l);
            _returnArrayVal1.setWaitingTime(_returnArrayVal1WaitingTime);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1WorkingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1WorkingTime.setValue(-815634370349032791l);
            _returnArrayVal1.setWorkingTime(_returnArrayVal1WorkingTime);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.TrackingService#requestVehiclePosition(com.wirelesscar.dynafleet.api.types.ApiTrackingRequestVehiclePositionTO  apiTrackingRequestVehiclePositionTO1 )*
     */
    public void requestVehiclePosition(com.wirelesscar.dynafleet.api.types.ApiTrackingRequestVehiclePositionTO apiTrackingRequestVehiclePositionTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation requestVehiclePosition");
        System.out.println(apiTrackingRequestVehiclePositionTO1);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.TrackingService#getNewTrackingDataV2(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiTrackingDataV2ArrayTO getNewTrackingDataV2(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getNewTrackingDataV2");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiTrackingDataV2ArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiTrackingDataV2ArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiTrackingDataV2TO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiTrackingDataV2TO>();
            com.wirelesscar.dynafleet.api.types.ApiTrackingDataV2TO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiTrackingDataV2TO();
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AccumulAdBlueConsumtion = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AccumulAdBlueConsumtion.setValue(-2318764074610920781l);
            _returnArrayVal1.setAccumulAdBlueConsumtion(_returnArrayVal1AccumulAdBlueConsumtion);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AccumulatedFuelConsumption = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AccumulatedFuelConsumption.setValue(2223266120624074959l);
            _returnArrayVal1.setAccumulatedFuelConsumption(_returnArrayVal1AccumulatedFuelConsumption);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1AdBlueLevelChangeMm = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1AdBlueLevelChangeMm.setValue(-751487186759653431l);
            _returnArrayVal1.setAdBlueLevelChangeMm(_returnArrayVal1AdBlueLevelChangeMm);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoDefrostOn = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoDefrostOn.setValue(true);
            _returnArrayVal1.setCargoDefrostOn(_returnArrayVal1CargoDefrostOn);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoDoorOpen = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoDoorOpen.setValue(false);
            _returnArrayVal1.setCargoDoorOpen(_returnArrayVal1CargoDoorOpen);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature1 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature1.setValue(4383375164610180959l);
            _returnArrayVal1.setCargoTemperature1(_returnArrayVal1CargoTemperature1);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature1Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature1Alarm.setValue(false);
            _returnArrayVal1.setCargoTemperature1Alarm(_returnArrayVal1CargoTemperature1Alarm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature2 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature2.setValue(1480886393803499244l);
            _returnArrayVal1.setCargoTemperature2(_returnArrayVal1CargoTemperature2);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature2Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature2Alarm.setValue(true);
            _returnArrayVal1.setCargoTemperature2Alarm(_returnArrayVal1CargoTemperature2Alarm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature3 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature3.setValue(-5367525516639924240l);
            _returnArrayVal1.setCargoTemperature3(_returnArrayVal1CargoTemperature3);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature3Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature3Alarm.setValue(true);
            _returnArrayVal1.setCargoTemperature3Alarm(_returnArrayVal1CargoTemperature3Alarm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature4 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature4.setValue(-5364986551789409079l);
            _returnArrayVal1.setCargoTemperature4(_returnArrayVal1CargoTemperature4);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnArrayVal1CargoTemperature4Alarm = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnArrayVal1CargoTemperature4Alarm.setValue(false);
            _returnArrayVal1.setCargoTemperature4Alarm(_returnArrayVal1CargoTemperature4Alarm);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature5 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature5.setValue(8985424412610168827l);
            _returnArrayVal1.setCargoTemperature5(_returnArrayVal1CargoTemperature5);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature6 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature6.setValue(373298489502312032l);
            _returnArrayVal1.setCargoTemperature6(_returnArrayVal1CargoTemperature6);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature7 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature7.setValue(-6792802309140719817l);
            _returnArrayVal1.setCargoTemperature7(_returnArrayVal1CargoTemperature7);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1CargoTemperature8 = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1CargoTemperature8.setValue(-2084558111548094189l);
            _returnArrayVal1.setCargoTemperature8(_returnArrayVal1CargoTemperature8);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1CurrentAdBlueLevel = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1CurrentAdBlueLevel.setValue(0.7806365f);
            _returnArrayVal1.setCurrentAdBlueLevel(_returnArrayVal1CurrentAdBlueLevel);
            _returnArrayVal1.setCurrentDriverActivity("CurrentDriverActivity706219112");
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1CurrentFuelLevel = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1CurrentFuelLevel.setValue(0.69577676f);
            _returnArrayVal1.setCurrentFuelLevel(_returnArrayVal1CurrentFuelLevel);
            com.wirelesscar.dynafleet.api.types.ApiPointTO _returnArrayVal1DestinationPoint = new com.wirelesscar.dynafleet.api.types.ApiPointTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1DestinationPointLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1DestinationPointLatitude.setValue(0.9927372021975347);
            _returnArrayVal1DestinationPoint.setLatitude(_returnArrayVal1DestinationPointLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1DestinationPointLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1DestinationPointLongitude.setValue(0.7445617425780698);
            _returnArrayVal1DestinationPoint.setLongitude(_returnArrayVal1DestinationPointLongitude);
            _returnArrayVal1.setDestinationPoint(_returnArrayVal1DestinationPoint);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1DistanceToDestination = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1DistanceToDestination.setValue(9214938456749286924l);
            _returnArrayVal1.setDistanceToDestination(_returnArrayVal1DistanceToDestination);
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(4989048136127896030l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1DrivingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1DrivingTime.setValue(-3312309791911385387l);
            _returnArrayVal1.setDrivingTime(_returnArrayVal1DrivingTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1EtaTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1EtaTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.585-05:00"));
            _returnArrayVal1.setEtaTime(_returnArrayVal1EtaTime);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1FrontAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1FrontAxleWeight.setValue(-6758722651360464963l);
            _returnArrayVal1.setFrontAxleWeight(_returnArrayVal1FrontAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1FuelLevelChange = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1FuelLevelChange.setValue(0.0053121448f);
            _returnArrayVal1.setFuelLevelChange(_returnArrayVal1FuelLevelChange);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1MomentaneousVehicleSpeed = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1MomentaneousVehicleSpeed.setValue(-5270027158502334390l);
            _returnArrayVal1.setMomentaneousVehicleSpeed(_returnArrayVal1MomentaneousVehicleSpeed);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1Odometer = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1Odometer.setValue(-1029302871105223287l);
            _returnArrayVal1.setOdometer(_returnArrayVal1Odometer);
            com.wirelesscar.dynafleet.api.types.ApiPositionTO _returnArrayVal1Position = new com.wirelesscar.dynafleet.api.types.ApiPositionTO();
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionAltitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionAltitude.setValue(0.19893300282719328);
            _returnArrayVal1Position.setAltitude(_returnArrayVal1PositionAltitude);
            com.wirelesscar.dynafleet.api.types.ApiFloat _returnArrayVal1PositionHeading = new com.wirelesscar.dynafleet.api.types.ApiFloat();
            _returnArrayVal1PositionHeading.setValue(0.18701994f);
            _returnArrayVal1Position.setHeading(_returnArrayVal1PositionHeading);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLatitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLatitude.setValue(0.5404792923630966);
            _returnArrayVal1Position.setLatitude(_returnArrayVal1PositionLatitude);
            com.wirelesscar.dynafleet.api.types.ApiDouble _returnArrayVal1PositionLongitude = new com.wirelesscar.dynafleet.api.types.ApiDouble();
            _returnArrayVal1PositionLongitude.setValue(0.5768031078323834);
            _returnArrayVal1Position.setLongitude(_returnArrayVal1PositionLongitude);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionPositionTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionPositionTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.585-05:00"));
            _returnArrayVal1Position.setPositionTime(_returnArrayVal1PositionPositionTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1PositionReceivedTime = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1PositionReceivedTime.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.586-05:00"));
            _returnArrayVal1Position.setReceivedTime(_returnArrayVal1PositionReceivedTime);
            _returnArrayVal1.setPosition(_returnArrayVal1Position);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RearAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RearAxleWeight.setValue(-3121446960738978393l);
            _returnArrayVal1.setRearAxleWeight(_returnArrayVal1RearAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RestingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RestingTime.setValue(-2106218175076233391l);
            _returnArrayVal1.setRestingTime(_returnArrayVal1RestingTime);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnArrayVal1Timestamp = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnArrayVal1Timestamp.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.586-05:00"));
            _returnArrayVal1.setTimestamp(_returnArrayVal1Timestamp);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TotalWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TotalWeight.setValue(-91632576505881056l);
            _returnArrayVal1.setTotalWeight(_returnArrayVal1TotalWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerFrontAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerFrontAxleWeight.setValue(3860809845476295206l);
            _returnArrayVal1.setTrailerFrontAxleWeight(_returnArrayVal1TrailerFrontAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerRearAxleWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerRearAxleWeight.setValue(-2841549308315269409l);
            _returnArrayVal1.setTrailerRearAxleWeight(_returnArrayVal1TrailerRearAxleWeight);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1TrailerTotalWeight = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1TrailerTotalWeight.setValue(4636899912701143659l);
            _returnArrayVal1.setTrailerTotalWeight(_returnArrayVal1TrailerTotalWeight);
            _returnArrayVal1.setTriggerType("TriggerType-385545066");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnArrayVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnArrayVal1VehicleId.setId(3673130179221112815l);
            _returnArrayVal1.setVehicleId(_returnArrayVal1VehicleId);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1WaitingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1WaitingTime.setValue(1882490683225303520l);
            _returnArrayVal1.setWaitingTime(_returnArrayVal1WaitingTime);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1WorkingTime = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1WorkingTime.setValue(-8509276028189175215l);
            _returnArrayVal1.setWorkingTime(_returnArrayVal1WorkingTime);
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

}
