
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.wirelesscar.dynafleet.api;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.608-05:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "DynafleetAPI",
                      portName = "VehicleAndDriverAdminServicePort",
                      targetNamespace = "http://wirelesscar.com/dynafleet/api",
                      wsdlLocation = "https://api-preprod.dynafleetonline.com/wsdl",
                      endpointInterface = "com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService")
                      
public class VehicleAndDriverAdminServiceImpl implements VehicleAndDriverAdminService {

    private static final Logger LOG = Logger.getLogger(VehicleAndDriverAdminServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getVehicle(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetVehicleTO  apiVADAdminGetVehicleTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiVehicleTO getVehicle(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetVehicleTO apiVADAdminGetVehicleTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getVehicle");
        System.out.println(apiVADAdminGetVehicleTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiVehicleTO _return = new com.wirelesscar.dynafleet.api.types.ApiVehicleTO();
            _return.setVIN("VIN-1045538424");
            com.wirelesscar.dynafleet.api.types.ApiLong _returnCurrentOdometerValue = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnCurrentOdometerValue.setValue(-2172661012370753239l);
            _return.setCurrentOdometerValue(_returnCurrentOdometerValue);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnCurrentOdometerValueDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnCurrentOdometerValueDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.613-05:00"));
            _return.setCurrentOdometerValueDate(_returnCurrentOdometerValueDate);
            _return.setDescription("Description1365334132");
            _return.setDisplayName("DisplayName1039080687");
            _return.setDistrict("District-647261096");
            _return.setDynafleetUnitNumber("DynafleetUnitNumber2110535393");
            _return.setEmail("Email1711157215");
            _return.setEmailAlias("EmailAlias-521627311");
            _return.setEmissionType("EmissionType-1181293064");
            _return.setEquipmentType("EquipmentType-1319707701");
            _return.setEuroClass("EuroClass-932147275");
            com.wirelesscar.dynafleet.api.types.ApiLong _returnExpectedYearlyMileage = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnExpectedYearlyMileage.setValue(7811448345204781604l);
            _return.setExpectedYearlyMileage(_returnExpectedYearlyMileage);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnForwardAssistanceRequestToVAS = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnForwardAssistanceRequestToVAS.setValue(false);
            _return.setForwardAssistanceRequestToVAS(_returnForwardAssistanceRequestToVAS);
            _return.setFuelQuality("FuelQuality895829167");
            _return.setGprsSettings("GprsSettings1044033639");
            _return.setGrossCombinationWeight("GrossCombinationWeight1046145100");
            _return.setGsmDataNr("GsmDataNr806219324");
            _return.setGsmPhoneNr("GsmPhoneNr1395402702");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnInstallationTestDone = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnInstallationTestDone.setValue(true);
            _return.setInstallationTestDone(_returnInstallationTestDone);
            _return.setInstallationTestResult("InstallationTestResult559404036");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnIsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnIsDeleted.setValue(false);
            _return.setIsDeleted(_returnIsDeleted);
            _return.setMake("Make1067627166");
            _return.setMarketSegment("MarketSegment-123105126");
            _return.setOperator("Operator227874020");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnParticleFilterInstalled = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnParticleFilterInstalled.setValue(true);
            _return.setParticleFilterInstalled(_returnParticleFilterInstalled);
            _return.setRegistrationCountry("RegistrationCountry561845183");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnRegistrationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnRegistrationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.613-05:00"));
            _return.setRegistrationDate(_returnRegistrationDate);
            _return.setRegistrationNumber("RegistrationNumber-113180367");
            _return.setRoadSurface("RoadSurface-1465028433");
            _return.setServicePack("ServicePack-1732348709");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnVehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnVehicleId.setId(-3499992211304474320l);
            _return.setVehicleId(_returnVehicleId);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getVehicles(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO getVehicles(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getVehicles");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO> _returnVehicleInfos = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO _returnVehicleInfosVal1 = new com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO();
            _returnVehicleInfosVal1.setDisplayName("DisplayName546415543");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnVehicleInfosVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnVehicleInfosVal1VehicleId.setId(-7323448496128657010l);
            _returnVehicleInfosVal1.setVehicleId(_returnVehicleInfosVal1VehicleId);
            _returnVehicleInfos.add(_returnVehicleInfosVal1);
            _return.getVehicleInfos().addAll(_returnVehicleInfos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getFleetInfo(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiFleetInfoTO getFleetInfo(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getFleetInfo");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiFleetInfoTO _return = new com.wirelesscar.dynafleet.api.types.ApiFleetInfoTO();
            _return.setCustomerDisplayname("CustomerDisplayname-1543752012");
            _return.setDisplayName("DisplayName-677801089");
            _return.setEmailAlias("EmailAlias-1615201199");
            com.wirelesscar.dynafleet.api.types.ApiLong _returnFleetId = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnFleetId.setValue(4398944731684131168l);
            _return.setFleetId(_returnFleetId);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnIsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnIsDeleted.setValue(false);
            _return.setIsDeleted(_returnIsDeleted);
            _return.setMeasureType("MeasureType-698240515");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDeletedVehicles(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO getDeletedVehicles(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDeletedVehicles");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO> _returnVehicleInfos = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO _returnVehicleInfosVal1 = new com.wirelesscar.dynafleet.api.types.ApiVehicleInfoTO();
            _returnVehicleInfosVal1.setDisplayName("DisplayName1466502852");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnVehicleInfosVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnVehicleInfosVal1VehicleId.setId(4521688326003199218l);
            _returnVehicleInfosVal1.setVehicleId(_returnVehicleInfosVal1VehicleId);
            _returnVehicleInfos.add(_returnVehicleInfosVal1);
            _return.getVehicleInfos().addAll(_returnVehicleInfos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDrivers(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO getDrivers(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDrivers");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO> _returnDriverInfos = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO _returnDriverInfosVal1 = new com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO();
            _returnDriverInfosVal1.setDisplayName("DisplayName-1960951276");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnDriverInfosVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnDriverInfosVal1DriverId.setId(-5962872016511536424l);
            _returnDriverInfosVal1.setDriverId(_returnDriverInfosVal1DriverId);
            _returnDriverInfos.add(_returnDriverInfosVal1);
            _return.getDriverInfos().addAll(_returnDriverInfos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getUsersAssignedToVehicle(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetUsersAssignedToVehicleTO  apiVADAdminGetUsersAssignedToVehicleTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiUserIdArrayTO getUsersAssignedToVehicle(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetUsersAssignedToVehicleTO apiVADAdminGetUsersAssignedToVehicleTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getUsersAssignedToVehicle");
        System.out.println(apiVADAdminGetUsersAssignedToVehicleTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiUserIdArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiUserIdArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiUserId> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiUserId>();
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnArrayVal1.setId(Long.valueOf(-6628341101230237149l));
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getUsers(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiUserArrayTO getUsers(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getUsers");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiUserArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiUserArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiUserTO> _returnUsers = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiUserTO>();
            com.wirelesscar.dynafleet.api.types.ApiUserTO _returnUsersVal1 = new com.wirelesscar.dynafleet.api.types.ApiUserTO();
            com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _returnUsersVal1AssignedDrivers = new com.wirelesscar.dynafleet.api.types.ApiLongArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiLong> _returnUsersVal1AssignedDriversArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLong>();
            _returnUsersVal1AssignedDrivers.getArray().addAll(_returnUsersVal1AssignedDriversArray);
            _returnUsersVal1.setAssignedDrivers(_returnUsersVal1AssignedDrivers);
            com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _returnUsersVal1AssignedVehicles = new com.wirelesscar.dynafleet.api.types.ApiLongArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiLong> _returnUsersVal1AssignedVehiclesArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLong>();
            _returnUsersVal1AssignedVehicles.getArray().addAll(_returnUsersVal1AssignedVehiclesArray);
            _returnUsersVal1.setAssignedVehicles(_returnUsersVal1AssignedVehicles);
            _returnUsersVal1.setDescription("Description349766894");
            _returnUsersVal1.setEmail("Email-670757982");
            _returnUsersVal1.setEmailAlias("EmailAlias1402319658");
            _returnUsersVal1.setFirstName("FirstName1375345515");
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnUsersVal1Id = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnUsersVal1Id.setId(Long.valueOf(9204931660026889272l));
            _returnUsersVal1.setId(_returnUsersVal1Id);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnUsersVal1IsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnUsersVal1IsDeleted.setValue(true);
            _returnUsersVal1.setIsDeleted(_returnUsersVal1IsDeleted);
            _returnUsersVal1.setLanguage("Language-181364488");
            _returnUsersVal1.setLastName("LastName207291933");
            _returnUsersVal1.setLoginname("Loginname-14263570");
            _returnUsersVal1.setMeasureType("MeasureType-1124928915");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnUsersVal1ShowCommunicationCostWarning = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnUsersVal1ShowCommunicationCostWarning.setValue(false);
            _returnUsersVal1.setShowCommunicationCostWarning(_returnUsersVal1ShowCommunicationCostWarning);
            java.util.List<java.lang.String> _returnUsersVal1UserRoles = new java.util.ArrayList<java.lang.String>();
            _returnUsersVal1.getUserRoles().addAll(_returnUsersVal1UserRoles);
            _returnUsers.add(_returnUsersVal1);
            _return.getUsers().addAll(_returnUsers);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDeletedUsers(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiUserInfoArrayTO getDeletedUsers(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDeletedUsers");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiUserInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiUserInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiUserInfoTO> _returnUsers = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiUserInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiUserInfoTO _returnUsersVal1 = new com.wirelesscar.dynafleet.api.types.ApiUserInfoTO();
            _returnUsersVal1.setDisplayName("DisplayName691170863");
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnUsersVal1UserId = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnUsersVal1UserId.setId(Long.valueOf(3994485700765807713l));
            _returnUsersVal1.setUserId(_returnUsersVal1UserId);
            _returnUsers.add(_returnUsersVal1);
            _return.getUsers().addAll(_returnUsers);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getModifiedUsers(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiUserArrayTO getModifiedUsers(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getModifiedUsers");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiUserArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiUserArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiUserTO> _returnUsers = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiUserTO>();
            com.wirelesscar.dynafleet.api.types.ApiUserTO _returnUsersVal1 = new com.wirelesscar.dynafleet.api.types.ApiUserTO();
            com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _returnUsersVal1AssignedDrivers = new com.wirelesscar.dynafleet.api.types.ApiLongArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiLong> _returnUsersVal1AssignedDriversArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLong>();
            _returnUsersVal1AssignedDrivers.getArray().addAll(_returnUsersVal1AssignedDriversArray);
            _returnUsersVal1.setAssignedDrivers(_returnUsersVal1AssignedDrivers);
            com.wirelesscar.dynafleet.api.types.ApiLongArrayTO _returnUsersVal1AssignedVehicles = new com.wirelesscar.dynafleet.api.types.ApiLongArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiLong> _returnUsersVal1AssignedVehiclesArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiLong>();
            _returnUsersVal1AssignedVehicles.getArray().addAll(_returnUsersVal1AssignedVehiclesArray);
            _returnUsersVal1.setAssignedVehicles(_returnUsersVal1AssignedVehicles);
            _returnUsersVal1.setDescription("Description-1097272526");
            _returnUsersVal1.setEmail("Email1312276838");
            _returnUsersVal1.setEmailAlias("EmailAlias1235040308");
            _returnUsersVal1.setFirstName("FirstName-1684148827");
            com.wirelesscar.dynafleet.api.types.ApiUserId _returnUsersVal1Id = new com.wirelesscar.dynafleet.api.types.ApiUserId();
            _returnUsersVal1Id.setId(Long.valueOf(2903993930492767130l));
            _returnUsersVal1.setId(_returnUsersVal1Id);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnUsersVal1IsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnUsersVal1IsDeleted.setValue(true);
            _returnUsersVal1.setIsDeleted(_returnUsersVal1IsDeleted);
            _returnUsersVal1.setLanguage("Language-298513262");
            _returnUsersVal1.setLastName("LastName-31493477");
            _returnUsersVal1.setLoginname("Loginname-2055633053");
            _returnUsersVal1.setMeasureType("MeasureType-2044655769");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnUsersVal1ShowCommunicationCostWarning = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnUsersVal1ShowCommunicationCostWarning.setValue(false);
            _returnUsersVal1.setShowCommunicationCostWarning(_returnUsersVal1ShowCommunicationCostWarning);
            java.util.List<java.lang.String> _returnUsersVal1UserRoles = new java.util.ArrayList<java.lang.String>();
            _returnUsersVal1.getUserRoles().addAll(_returnUsersVal1UserRoles);
            _returnUsers.add(_returnUsersVal1);
            _return.getUsers().addAll(_returnUsers);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getVehiclesV2(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2ArrayTO getVehiclesV2(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getVehiclesV2");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2ArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2ArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2TO> _returnVehicleInfos = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2TO>();
            com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2TO _returnVehicleInfosVal1 = new com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2TO();
            _returnVehicleInfosVal1.setDisplayName("DisplayName-683485024");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnVehicleInfosVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnVehicleInfosVal1VehicleId.setId(-7012911803404515109l);
            _returnVehicleInfosVal1.setVehicleId(_returnVehicleInfosVal1VehicleId);
            _returnVehicleInfosVal1.setVin("Vin815322371");
            _returnVehicleInfos.add(_returnVehicleInfosVal1);
            _return.getVehicleInfos().addAll(_returnVehicleInfos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getModifiedVehicles(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiVehicleArrayTO getModifiedVehicles(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getModifiedVehicles");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiVehicleArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiVehicleArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiVehicleTO> _returnVehicles = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiVehicleTO>();
            com.wirelesscar.dynafleet.api.types.ApiVehicleTO _returnVehiclesVal1 = new com.wirelesscar.dynafleet.api.types.ApiVehicleTO();
            _returnVehiclesVal1.setVIN("VIN1726428304");
            com.wirelesscar.dynafleet.api.types.ApiLong _returnVehiclesVal1CurrentOdometerValue = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnVehiclesVal1CurrentOdometerValue.setValue(-1763873174772351954l);
            _returnVehiclesVal1.setCurrentOdometerValue(_returnVehiclesVal1CurrentOdometerValue);
            com.wirelesscar.dynafleet.api.types.ApiDate _returnVehiclesVal1CurrentOdometerValueDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnVehiclesVal1CurrentOdometerValueDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.617-05:00"));
            _returnVehiclesVal1.setCurrentOdometerValueDate(_returnVehiclesVal1CurrentOdometerValueDate);
            _returnVehiclesVal1.setDescription("Description-556013615");
            _returnVehiclesVal1.setDisplayName("DisplayName-1090768604");
            _returnVehiclesVal1.setDistrict("District-1049466804");
            _returnVehiclesVal1.setDynafleetUnitNumber("DynafleetUnitNumber1029586609");
            _returnVehiclesVal1.setEmail("Email-793594777");
            _returnVehiclesVal1.setEmailAlias("EmailAlias1151092866");
            _returnVehiclesVal1.setEmissionType("EmissionType670939248");
            _returnVehiclesVal1.setEquipmentType("EquipmentType1460821091");
            _returnVehiclesVal1.setEuroClass("EuroClass-862928307");
            com.wirelesscar.dynafleet.api.types.ApiLong _returnVehiclesVal1ExpectedYearlyMileage = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnVehiclesVal1ExpectedYearlyMileage.setValue(1767884462711031028l);
            _returnVehiclesVal1.setExpectedYearlyMileage(_returnVehiclesVal1ExpectedYearlyMileage);
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnVehiclesVal1ForwardAssistanceRequestToVAS = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnVehiclesVal1ForwardAssistanceRequestToVAS.setValue(true);
            _returnVehiclesVal1.setForwardAssistanceRequestToVAS(_returnVehiclesVal1ForwardAssistanceRequestToVAS);
            _returnVehiclesVal1.setFuelQuality("FuelQuality140732376");
            _returnVehiclesVal1.setGprsSettings("GprsSettings63987320");
            _returnVehiclesVal1.setGrossCombinationWeight("GrossCombinationWeight-1426142010");
            _returnVehiclesVal1.setGsmDataNr("GsmDataNr-1945759083");
            _returnVehiclesVal1.setGsmPhoneNr("GsmPhoneNr-2145369904");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnVehiclesVal1InstallationTestDone = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnVehiclesVal1InstallationTestDone.setValue(true);
            _returnVehiclesVal1.setInstallationTestDone(_returnVehiclesVal1InstallationTestDone);
            _returnVehiclesVal1.setInstallationTestResult("InstallationTestResult1333920048");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnVehiclesVal1IsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnVehiclesVal1IsDeleted.setValue(false);
            _returnVehiclesVal1.setIsDeleted(_returnVehiclesVal1IsDeleted);
            _returnVehiclesVal1.setMake("Make863103825");
            _returnVehiclesVal1.setMarketSegment("MarketSegment248432012");
            _returnVehiclesVal1.setOperator("Operator-1609963684");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnVehiclesVal1ParticleFilterInstalled = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnVehiclesVal1ParticleFilterInstalled.setValue(false);
            _returnVehiclesVal1.setParticleFilterInstalled(_returnVehiclesVal1ParticleFilterInstalled);
            _returnVehiclesVal1.setRegistrationCountry("RegistrationCountry-881250570");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnVehiclesVal1RegistrationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnVehiclesVal1RegistrationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.617-05:00"));
            _returnVehiclesVal1.setRegistrationDate(_returnVehiclesVal1RegistrationDate);
            _returnVehiclesVal1.setRegistrationNumber("RegistrationNumber-1858023067");
            _returnVehiclesVal1.setRoadSurface("RoadSurface-1791898087");
            _returnVehiclesVal1.setServicePack("ServicePack1954749206");
            com.wirelesscar.dynafleet.api.types.ApiVehicleId _returnVehiclesVal1VehicleId = new com.wirelesscar.dynafleet.api.types.ApiVehicleId();
            _returnVehiclesVal1VehicleId.setId(-4587212868624991639l);
            _returnVehiclesVal1.setVehicleId(_returnVehiclesVal1VehicleId);
            _returnVehicles.add(_returnVehiclesVal1);
            _return.getVehicles().addAll(_returnVehicles);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDriver(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverTO  apiVADAdminGetDriverTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDriverTO getDriver(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverTO apiVADAdminGetDriverTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDriver");
        System.out.println(apiVADAdminGetDriverTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDriverTO _return = new com.wirelesscar.dynafleet.api.types.ApiDriverTO();
            _return.setADRLicense("ADRLicense-399615009");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnADRLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnADRLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.618-05:00"));
            _return.setADRLicenseExpirationDate(_returnADRLicenseExpirationDate);
            _return.setAdditionalDriverInformation("AdditionalDriverInformation-462290513");
            _return.setAdditionalLicense("AdditionalLicense-1298816510");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnAdditionalLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnAdditionalLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.618-05:00"));
            _return.setAdditionalLicenseExpirationDate(_returnAdditionalLicenseExpirationDate);
            _return.setAddress("Address81295823");
            _return.setCity("City177568016");
            _return.setCountry("Country1001428397");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnDriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnDriverId.setId(-8876894204228074028l);
            _return.setDriverId(_returnDriverId);
            _return.setDriverLicense("DriverLicense-1438377344");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnDriverLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnDriverLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.619-05:00"));
            _return.setDriverLicenseExpirationDate(_returnDriverLicenseExpirationDate);
            _return.setDrivingPattern("DrivingPattern-1195455049");
            _return.setEmail("Email810879322");
            _return.setEmploymentType("EmploymentType-1272737515");
            _return.setFirstName("FirstName-461918153");
            _return.setHomePhone("HomePhone-661846219");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnIsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnIsDeleted.setValue(false);
            _return.setIsDeleted(_returnIsDeleted);
            _return.setLastName("LastName-89003232");
            _return.setMedicalCheckup("MedicalCheckup1078541429");
            _return.setMobile("Mobile1128426240");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnPassPortExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnPassPortExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.619-05:00"));
            _return.setPassPortExpirationDate(_returnPassPortExpirationDate);
            _return.setPassportNumber("PassportNumber-380121336");
            _return.setSocialSecurityNumber("SocialSecurityNumber-3549625");
            _return.setZipCode("ZipCode-820750602");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDeletedDrivers(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO getDeletedDrivers(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDeletedDrivers");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO> _returnDriverInfos = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO>();
            com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO _returnDriverInfosVal1 = new com.wirelesscar.dynafleet.api.types.ApiDriverInfoTO();
            _returnDriverInfosVal1.setDisplayName("DisplayName532179288");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnDriverInfosVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnDriverInfosVal1DriverId.setId(3307469959158326968l);
            _returnDriverInfosVal1.setDriverId(_returnDriverInfosVal1DriverId);
            _returnDriverInfos.add(_returnDriverInfosVal1);
            _return.getDriverInfos().addAll(_returnDriverInfos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getModifiedDrivers(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDriverArrayTO getModifiedDrivers(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getModifiedDrivers");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDriverArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDriverArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDriverTO> _returnDrivers = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDriverTO>();
            com.wirelesscar.dynafleet.api.types.ApiDriverTO _returnDriversVal1 = new com.wirelesscar.dynafleet.api.types.ApiDriverTO();
            _returnDriversVal1.setADRLicense("ADRLicense-1187733386");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnDriversVal1ADRLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnDriversVal1ADRLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.620-05:00"));
            _returnDriversVal1.setADRLicenseExpirationDate(_returnDriversVal1ADRLicenseExpirationDate);
            _returnDriversVal1.setAdditionalDriverInformation("AdditionalDriverInformation731742490");
            _returnDriversVal1.setAdditionalLicense("AdditionalLicense1434355771");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnDriversVal1AdditionalLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnDriversVal1AdditionalLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.621-05:00"));
            _returnDriversVal1.setAdditionalLicenseExpirationDate(_returnDriversVal1AdditionalLicenseExpirationDate);
            _returnDriversVal1.setAddress("Address-558383414");
            _returnDriversVal1.setCity("City455633526");
            _returnDriversVal1.setCountry("Country-1499412942");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnDriversVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnDriversVal1DriverId.setId(-7406202595231286119l);
            _returnDriversVal1.setDriverId(_returnDriversVal1DriverId);
            _returnDriversVal1.setDriverLicense("DriverLicense-2100324544");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnDriversVal1DriverLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnDriversVal1DriverLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.621-05:00"));
            _returnDriversVal1.setDriverLicenseExpirationDate(_returnDriversVal1DriverLicenseExpirationDate);
            _returnDriversVal1.setDrivingPattern("DrivingPattern522902350");
            _returnDriversVal1.setEmail("Email-1695631932");
            _returnDriversVal1.setEmploymentType("EmploymentType-635999020");
            _returnDriversVal1.setFirstName("FirstName-227936727");
            _returnDriversVal1.setHomePhone("HomePhone1178620627");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnDriversVal1IsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnDriversVal1IsDeleted.setValue(true);
            _returnDriversVal1.setIsDeleted(_returnDriversVal1IsDeleted);
            _returnDriversVal1.setLastName("LastName560223956");
            _returnDriversVal1.setMedicalCheckup("MedicalCheckup-278355946");
            _returnDriversVal1.setMobile("Mobile427076372");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnDriversVal1PassPortExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnDriversVal1PassPortExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.622-05:00"));
            _returnDriversVal1.setPassPortExpirationDate(_returnDriversVal1PassPortExpirationDate);
            _returnDriversVal1.setPassportNumber("PassportNumber264180890");
            _returnDriversVal1.setSocialSecurityNumber("SocialSecurityNumber1241642481");
            _returnDriversVal1.setZipCode("ZipCode1918507072");
            _returnDrivers.add(_returnDriversVal1);
            _return.getDrivers().addAll(_returnDrivers);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDriverTimes(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverTimesTO  apiVADAdminGetDriverTimesTO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDriverTimesArrayTO getDriverTimes(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverTimesTO apiVADAdminGetDriverTimesTO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDriverTimes");
        System.out.println(apiVADAdminGetDriverTimesTO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDriverTimesArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDriverTimesArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDriverTimesTO> _returnArray = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDriverTimesTO>();
            com.wirelesscar.dynafleet.api.types.ApiDriverTimesTO _returnArrayVal1 = new com.wirelesscar.dynafleet.api.types.ApiDriverTimesTO();
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnArrayVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnArrayVal1DriverId.setId(6671055632283722059l);
            _returnArrayVal1.setDriverId(_returnArrayVal1DriverId);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RemainingDrivingTimeCurrentSession = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RemainingDrivingTimeCurrentSession.setValue(5990055859117438267l);
            _returnArrayVal1.setRemainingDrivingTimeCurrentSession(_returnArrayVal1RemainingDrivingTimeCurrentSession);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RemainingDrivingTimeToday = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RemainingDrivingTimeToday.setValue(-6043942175376572842l);
            _returnArrayVal1.setRemainingDrivingTimeToday(_returnArrayVal1RemainingDrivingTimeToday);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RemainingDrivingTimeThisWeek = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RemainingDrivingTimeThisWeek.setValue(-890875445017110989l);
            _returnArrayVal1.setRemainingDrivingTimeThisWeek(_returnArrayVal1RemainingDrivingTimeThisWeek);
            com.wirelesscar.dynafleet.api.types.ApiLong _returnArrayVal1RemainingDrivingTimeLastTwoWeeks = new com.wirelesscar.dynafleet.api.types.ApiLong();
            _returnArrayVal1RemainingDrivingTimeLastTwoWeeks.setValue(9013661580466259035l);
            _returnArrayVal1.setRemainingDrivingTimeLastTwoWeeks(_returnArrayVal1RemainingDrivingTimeLastTwoWeeks);
            _returnArrayVal1.setInfringementTime("InfringementTime1303979527");
            _returnArrayVal1.setInfringementDescription("InfringementDescription660121721");
            _returnArrayVal1.setNextRestDescription("NextRestDescription1899343690");
            _returnArray.add(_returnArrayVal1);
            _return.getArray().addAll(_returnArray);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDriverV2(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverV2TO  apiVADAdminGetDriverV2TO1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDriverV2TO getDriverV2(com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverV2TO apiVADAdminGetDriverV2TO1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDriverV2");
        System.out.println(apiVADAdminGetDriverV2TO1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDriverV2TO _return = new com.wirelesscar.dynafleet.api.types.ApiDriverV2TO();
            _return.setADRLicense("ADRLicense-310355529");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnADRLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnADRLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.623-05:00"));
            _return.setADRLicenseExpirationDate(_returnADRLicenseExpirationDate);
            _return.setAdditionalDriverInformation("AdditionalDriverInformation-959936713");
            _return.setAdditionalLicense("AdditionalLicense1618247997");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnAdditionalLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnAdditionalLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.623-05:00"));
            _return.setAdditionalLicenseExpirationDate(_returnAdditionalLicenseExpirationDate);
            _return.setAddress("Address1069914839");
            _return.setCity("City-1107940379");
            _return.setCountry("Country-2014371835");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnDriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnDriverId.setId(-7911118530492564430l);
            _return.setDriverId(_returnDriverId);
            _return.setDriverLicense("DriverLicense-2114610400");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnDriverLicenseExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnDriverLicenseExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.623-05:00"));
            _return.setDriverLicenseExpirationDate(_returnDriverLicenseExpirationDate);
            _return.setDrivingPattern("DrivingPattern2115589531");
            _return.setEmail("Email-1399887138");
            _return.setEmploymentType("EmploymentType-2055310388");
            _return.setFirstName("FirstName1866234955");
            _return.setHomePhone("HomePhone-1891576467");
            com.wirelesscar.dynafleet.api.types.ApiBoolean _returnIsDeleted = new com.wirelesscar.dynafleet.api.types.ApiBoolean();
            _returnIsDeleted.setValue(false);
            _return.setIsDeleted(_returnIsDeleted);
            _return.setLastName("LastName-944364384");
            _return.setMedicalCheckup("MedicalCheckup-463383275");
            _return.setMobile("Mobile1382762633");
            com.wirelesscar.dynafleet.api.types.ApiDate _returnPassPortExpirationDate = new com.wirelesscar.dynafleet.api.types.ApiDate();
            _returnPassPortExpirationDate.setValue(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-06-30T14:30:13.624-05:00"));
            _return.setPassPortExpirationDate(_returnPassPortExpirationDate);
            _return.setPassportNumber("PassportNumber-1644910249");
            _return.setSocialSecurityNumber("SocialSecurityNumber-675378775");
            _return.setZipCode("ZipCode-2038663592");
            _return.setDigitalTachoCardId("DigitalTachoCardId-1433376717");
            _return.setCardRegistredTo("CardRegistredTo1055580128");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

    /* (non-Javadoc)
     * @see com.wirelesscar.dynafleet.api.VehicleAndDriverAdminService#getDriversV2(com.wirelesscar.dynafleet.api.types.ApiSessionId  apiSessionId1 )*
     */
    public com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2ArrayTO getDriversV2(com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1) throws DynafleetAPIException    { 
        LOG.info("Executing operation getDriversV2");
        System.out.println(apiSessionId1);
        try {
            com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2ArrayTO _return = new com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2ArrayTO();
            java.util.List<com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2TO> _returnDriverInfos = new java.util.ArrayList<com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2TO>();
            com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2TO _returnDriverInfosVal1 = new com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2TO();
            _returnDriverInfosVal1.setDisplayName("DisplayName-1894338925");
            com.wirelesscar.dynafleet.api.types.ApiDriverId _returnDriverInfosVal1DriverId = new com.wirelesscar.dynafleet.api.types.ApiDriverId();
            _returnDriverInfosVal1DriverId.setId(-45642094425651280l);
            _returnDriverInfosVal1.setDriverId(_returnDriverInfosVal1DriverId);
            _returnDriverInfosVal1.setDigitalTachoCardId("DigitalTachoCardId-2090390479");
            _returnDriverInfosVal1.setCardRegistredTo("CardRegistredTo-2130001995");
            _returnDriverInfos.add(_returnDriverInfosVal1);
            _return.getDriverInfos().addAll(_returnDriverInfos);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new DynafleetAPIException("DynafleetAPIException...");
    }

}
