package com.wirelesscar.dynafleet.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2017-06-30T14:30:13.675-05:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://wirelesscar.com/dynafleet/api", name = "VehicleAndDriverAdminService")
@XmlSeeAlso({com.wirelesscar.dynafleet.api.types.ObjectFactory.class})
public interface VehicleAndDriverAdminService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVehicle", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicle")
    @WebMethod
    @ResponseWrapper(localName = "getVehicleResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicleResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleTO getVehicle(
        @WebParam(name = "Api_VADAdminGetVehicleTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiVADAdminGetVehicleTO apiVADAdminGetVehicleTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVehicles", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehicles")
    @WebMethod
    @ResponseWrapper(localName = "getVehiclesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehiclesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO getVehicles(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getFleetInfo", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetFleetInfo")
    @WebMethod
    @ResponseWrapper(localName = "getFleetInfoResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetFleetInfoResponse")
    public com.wirelesscar.dynafleet.api.types.ApiFleetInfoTO getFleetInfo(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeletedVehicles", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedVehicles")
    @WebMethod
    @ResponseWrapper(localName = "getDeletedVehiclesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedVehiclesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleInfoArrayTO getDeletedVehicles(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDrivers", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDrivers")
    @WebMethod
    @ResponseWrapper(localName = "getDriversResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriversResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO getDrivers(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getUsersAssignedToVehicle", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetUsersAssignedToVehicle")
    @WebMethod
    @ResponseWrapper(localName = "getUsersAssignedToVehicleResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetUsersAssignedToVehicleResponse")
    public com.wirelesscar.dynafleet.api.types.ApiUserIdArrayTO getUsersAssignedToVehicle(
        @WebParam(name = "Api_VADAdminGetUsersAssignedToVehicleTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiVADAdminGetUsersAssignedToVehicleTO apiVADAdminGetUsersAssignedToVehicleTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetUsers")
    @WebMethod
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetUsersResponse")
    public com.wirelesscar.dynafleet.api.types.ApiUserArrayTO getUsers(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeletedUsers", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedUsers")
    @WebMethod
    @ResponseWrapper(localName = "getDeletedUsersResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedUsersResponse")
    public com.wirelesscar.dynafleet.api.types.ApiUserInfoArrayTO getDeletedUsers(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getModifiedUsers", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedUsers")
    @WebMethod
    @ResponseWrapper(localName = "getModifiedUsersResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedUsersResponse")
    public com.wirelesscar.dynafleet.api.types.ApiUserArrayTO getModifiedUsers(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getVehiclesV2", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehiclesV2")
    @WebMethod
    @ResponseWrapper(localName = "getVehiclesV2Response", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetVehiclesV2Response")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleInfoV2ArrayTO getVehiclesV2(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getModifiedVehicles", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedVehicles")
    @WebMethod
    @ResponseWrapper(localName = "getModifiedVehiclesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedVehiclesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiVehicleArrayTO getModifiedVehicles(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDriver", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriver")
    @WebMethod
    @ResponseWrapper(localName = "getDriverResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriverResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDriverTO getDriver(
        @WebParam(name = "Api_VADAdminGetDriverTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverTO apiVADAdminGetDriverTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDeletedDrivers", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedDrivers")
    @WebMethod
    @ResponseWrapper(localName = "getDeletedDriversResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDeletedDriversResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDriverInfoArrayTO getDeletedDrivers(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getModifiedDrivers", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedDrivers")
    @WebMethod
    @ResponseWrapper(localName = "getModifiedDriversResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetModifiedDriversResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDriverArrayTO getModifiedDrivers(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDriverTimes", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriverTimes")
    @WebMethod
    @ResponseWrapper(localName = "getDriverTimesResponse", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriverTimesResponse")
    public com.wirelesscar.dynafleet.api.types.ApiDriverTimesArrayTO getDriverTimes(
        @WebParam(name = "ApiVADAdminGetDriverTimesTO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverTimesTO apiVADAdminGetDriverTimesTO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDriverV2", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriverV2")
    @WebMethod
    @ResponseWrapper(localName = "getDriverV2Response", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriverV2Response")
    public com.wirelesscar.dynafleet.api.types.ApiDriverV2TO getDriverV2(
        @WebParam(name = "Api_VADAdminGetDriverV2TO_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiVADAdminGetDriverV2TO apiVADAdminGetDriverV2TO1
    ) throws DynafleetAPIException;

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "getDriversV2", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriversV2")
    @WebMethod
    @ResponseWrapper(localName = "getDriversV2Response", targetNamespace = "http://wirelesscar.com/dynafleet/api/types", className = "com.wirelesscar.dynafleet.api.types.GetDriversV2Response")
    public com.wirelesscar.dynafleet.api.types.ApiDriverInfoV2ArrayTO getDriversV2(
        @WebParam(name = "Api_SessionId_1", targetNamespace = "")
        com.wirelesscar.dynafleet.api.types.ApiSessionId apiSessionId1
    ) throws DynafleetAPIException;
}
